### ISSUE TITLE
occurrence route doesn't exist anymore

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#100]
via email

```r
occurrence("Oncorhynchus mykiss")
#> Source: local data frame [0 x 0]
#> 
#> Warning messages:
#> 1: In check_and_parse(resp) : Bad Request (HTTP 400).
#> 2: In error_checks(parsed, resp = resp) :
#>   Mysql2::Error: Table 'fbapp.occurrence' doesn't exist: SHOW FULL FIELDS FROM `occurrence` for #> query https://fishbase.ropensci.org/occurrence?SpecCode=239&limit=200
```

**Comment by sckott** [comment]
@cboettig yeah, the occurrence table is gone in the new new SQL DB

I assume we should drop that route, and corresponding fxn in this pkg?

**Comment by cboettig** [comment]
Yup.  Maybe include a warning for now "this table is no longer available in the FishBase API"?  Guess we should write to Ranier and ask about the change

**Comment by sckott** [comment]
yeah, or rather a stop message?

**Comment by sckott** [comment]
sealifebase has `occurrence` table, but it's apparently empty, so I guess we can treat them the same essentially
