### ISSUE TITLE
New version to CRAN

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#101]
hey @cboettig I haven't been involved in when things are pushed to CRAN - are you using milestones to organize what issues go into a CRAN push?  Or not necessarily?  Seems like there's been lots of changes since last CRAN version from `2015-11-10`

**Comment by cboettig** [comment]
Good question.  I was loosely tagging issues into milestones but haven't kept up on that.  The past few releases have been just when CRAN has requested specific updates (usually related to testing, see https://github.com/ropensci/rfishbase/commits/master/cran-comments.md).  

But yeah, we should definitely do a CRAN push soon.  Are there any open issues we still want resolve before doing a CRAN release or should we just go for it asap?

**Comment by sckott** [comment]
i'll look over the issues today/tomorrow and suggest any that we should include, if any

**Comment by cboettig** [comment]
thanks for going through the outstanding issues.  I haven't done a good job of getting all the closed issues / bug-fixes mentioned and linked in the NEWS file for the next release.  Can you take a run through that and update NEWS as you close of issues for this release?

**Comment by sckott** [comment]
Yes, will update news, closing this now

**Comment by sckott** [comment]
I think I sorted all those relevant into 2.2.0 milestone, only one open is #62 which I can do soon
