### ISSUE TITLE
Issue with null returns from maturity()

### ISSUE THREAD

**Issue by tomjwebb** [ropensci/rfishbase#103]
Hi - been using the `maturity()` function to get length at maturity for a list of species (names validated for all). Problem is that if it fails for a single species in the list, the whole list fails. I have a workaround (see below) but wondered if it would be possible to return a null data frame if the function returns nothing? Here's an example:

Set up dummy species list

``` r
sp_list_test <- c("Limanda limanda", "Scophthalmus maximus", "Chelidonichthys lucerna", "Echiichthys vipera")
```

Try getting maturity data by passing vector of species

``` r
mat_dat <- maturity(sp_list_test)
```

This fails:

``` r
Error in names(data)[names(data) == "Speccode"] = "SpecCode" : 
  attempt to set an attribute on NULL
In addition: Warning messages:
1: In check_and_parse(resp) : Bad Request (HTTP 400).
2: In error_checks(parsed, resp = resp) :
  no results found for query https://fishbase.ropensci.org/maturity?Speccode=1366&limit=200
```

My bodged fix: loop over each species individually:

``` r
mat_dat <- sapply(sp_list_test, function(sp_list_test){try(maturity(sp_list_test), silent = T)})
lapply(mat_dat, class)
$`Limanda limanda`
[1] "tbl_df"     "tbl"        "data.frame"

$`Scophthalmus maximus`
[1] "tbl_df"     "tbl"        "data.frame"

$`Chelidonichthys lucerna`
[1] "try-error"

$`Echiichthys vipera`
[1] "try-error"
```

This works - returns data frame for successes and try-error for failures, but will need to piece together data frame afterwards - not really a problem, but would be preferable to be able to return straight off a single data frame with NULL values (apart from species name) for any species that returns nothing.

Relatedly - of the two species that fail in the above example, one (Echiichthys vipera) indeed has no maturity table in fishbase, but the other (Chelidonichthys lucerna) does, see: http://www.fishbase.org/Reproduction/MaturityList.php?ID=1366&GenusName=Chelidonichthys&SpeciesName=lucerna&fc=266 Any idea why it's not returning anything?

Thanks!

**Comment by tomjwebb** [comment]
Just to follow up on the above, this is my solution to turning the returned list into a single data frame, feels unnecessarily clumsy but it works…
``mat_dat <- mat_dat[which(lapply(mat_dat, class) != "try-error")]``
``mat_dat <- bind_rows(mat_dat)``
``null_df <- matrix(ncol = ncol(mat_dat), nrow = length(id_null_sp))``
``colnames(null_df) <- names(mat_dat)``
``null_df <- as.data.frame(null_df)``
``null_df$sciname <- sp_list_test[id_null_sp]``
``mat_dat <- rbind(mat_dat, null_df)``

**Comment by sckott** [comment]
Thanks for your report Tom!  

I'll have a look and see what's going on

**Comment by cboettig** [comment]
@sckott thanks!  Looks like check_and_parse() doesn't handle the case of no content after getting a 400 error, so that should be fixed (not at computer & not sure I want to patch it from my phone though).

Not sure why the API isn't returning any content though, seems like it should give an empty json return instead of 404?


The discrepancy between the online source might be fixed when we update the database(?)

**Comment by sckott** [comment]
@tomjwebb what version of `rfishbase` do you have?

**Comment by sckott** [comment]
ran into problems loading the new fishbase database, getting in touch with them now...

**Comment by tomjwebb** [comment]
@sckott Sorry, just seen your question, I'm running rfishbase 2.1.0.1 on R 3.2.3

**Comment by sckott** [comment]
@tomjwebb there is a newer version - reinstall like `devtools::install_github("ropensci/rfishbase")` and try again - the errors should be fixed, but those taxa missing still aren't there - waiting to hear back on fishbase DB problems

**Comment by tomjwebb** [comment]
@sckott Got it - works now, thanks! Trying to decide whether returning a single row of NAs (apart from sciname) for species returning no results might be more useful than just excluding them altogether from the returned tibble (see, I know the lingo!) - especially if I want to summarise the output to a single value per species, it would be useful to keep all species there. But that's maybe not appropriate for all use cases and is something that is very easy to do post-hoc, now you've sorted the main issue. So, thanks! Going to put it to use this morning…

**Comment by sckott** [comment]
seems fixed now, reopen if it's not really fixed
