### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#104]
@cboettig   - to be consistent across ropensci pkgs https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

is it okay if we use the [releases tab](https://github.com/ropensci/rfishbase/releases) to include the associated NEWS items for each tag/version ?

**Comment by cboettig** [comment]
:+1:

**Comment by sckott** [comment]
great
