### ISSUE TITLE
Provide image download function

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#11]
Image paths are included in the summary XML along with basic dublin core metadata.  Should be easy to extract.

**Comment by amroco** [comment]
Hi there, having a bit of trouble with this function:

> valid_name <- validate_names(c("Fodiator acutus"))
Warning: FishBase says that 'Fodiator acutus' can also be misapplied to other species
                    but is returning only the best match.  
                    See synonyms('Fodiator acutus') for details
> valid_name
[1] "Fodiator acutus"
> getPictures(valid_name[[1]], download=TRUE)
Error: could not find function "getPictures"

Any thoughts?
Thanks
