### ISSUE TITLE
password expired

### ISSUE THREAD

**Issue by rlopes2** [ropensci/rfishbase#112]
After installing rfishbase without problems, I follow the instructions in README.md and get an error:

> library(rfishbase)
> fish <- common_to_sci("trout")
Warning messages:
1: In check_and_parse(resp) : Bad Request (HTTP 400).
2: Your password has expired. To log in you must change it using a client that supports expired passwords. for query https://fishbase.ropensci.org/comnames?ComName=trout&limit=1000&fields=SpecCode

I tried on Linux (R 3.3.2) and Windows (R 3.1.2), and got the same error. Any help would be appreciated.

**Comment by sckott** [comment]
thanks for the report @rlopes2 - we're looking into this

**Comment by cboettig** [comment]
@rlopes2 Try now, should be fixed.

**Comment by rlopes2** [comment]
Works! Thank you for the quick fix.
