### ISSUE TITLE
Links/text about supporting fishbase in documentation

### ISSUE THREAD

**Issue by noamross** [ropensci/rfishbase#114]
Given FishBase's need for donations (https://twitter.com/FishBaseProject/status/829648513021595649) it might be nice to put a link to the donations page in the README, the package-level documentation, vingettes, and possibly the package start-up message.

Self-assigning this if others are OK with it.  Will do something like "FishBase is maintained by XXX...you may support XXX by donating at URL"

**Comment by cboettig** [comment]
Good idea. One concern I have is that this might further the already common confusion that this package and the API are directly supported by fishbase and not ropensci (as selfish as that is to mention).  The vignette  & readme could probably explain both issues though.  I'm not a fan of package startup messages, always feels like an ad asking me for money even when it isn't.  


 I wonder if the API base URL (fishbase.ropensci.org) ought to have a webpage about the API and mention this too.

PR on this would be great!

**Comment by sckott** [comment]
I can try a landing page for fishbase.ropensci.org - and we can iterate on that. 

for the pkg docs, i can add something to readme and vignette in PR so we can discuss

**Comment by sckott** [comment]
here's a first  mockup of a landing page 

![screen shot 2017-03-06 at 1 10 57 pm](https://cloud.githubusercontent.com/assets/577668/23630042/628b4208-026e-11e7-9815-9c15c144903f.png)

instead of having docs included, just link to our slate docs https://ropensci.github.io/fishbaseapidocs/ - need to make sure they're up to date of course

thoughts?

**Comment by cboettig** [comment]
:+1:

**Comment by sckott** [comment]
new landing page is up, a few things to tweak still https://github.com/ropensci/fishbaseapi/issues/108

**Comment by sckott** [comment]
anything else to do here @cboettig @noamross ?

**Comment by cboettig** [comment]
looks like we've done this, might be worth revisiting later
