### ISSUE TITLE
Access to "Estimates" Table

### ISSUE THREAD

**Issue by allimcg** [ropensci/rfishbase#115]
Hi! I wasn't sure where to ask this, let me know if I should post somewhere else!

I've been trying to access estimated tropic levels. On a species home page in FishBase, trophic level information is listed at the very bottom in a section titled "Estimates of some properties based on models", but it appears this information comes from a variety of sources. Sometime the trophic leveldata comes from Food or Diet studies--I've easily been able to access this information through the ecology table (FoodTroph and DietTroph). However, it seems FishBase has another method for estimating these tropic levels, using information on size and the trophic levels of closely relates species. Species with a trophic level determined using this method have the description "Based on size and trophs of closest relatives" next to the Trophic Level on their home page. According to FishBase resources, this information is stored in a table called "estimates":

"The trophic level estimates obtained in this fashion are stored separately from the observation-based values in the ECOLOGY table, in a new table called ESTIMATES. Continuous updating of FishBase will ensure that the troph and other estimates in that table are over-written as soon as observation-based values become available. (Users of the CD-ROM version of FishBase 2000 should visit the Internet version of FishBase for latest updates)." http://www.fishbase.us/manual/English/FishbaseThe_FOOD_ITEMS_table.htm

Is there a way to access this information? I haven't been able to figure out how to get to the estimates table. The ideal solution would be a way to retrieve whatever the trophic level is on the home page (be that a FoodTroph, DietTroph, or estimated trophic level) so that all queried species return the best-guess trophic level. 

Thank you for your help!

**Comment by sckott** [comment]
Hi @allimcg good question. 

I believe the table at least in the database is `estimates` instead of `estimate`

We have this table in the database, but it's not exposed in the API right now. 

I've opened an issue in our repo where we develop the API  - we'll have a look

**Comment by allimcg** [comment]
Thanks @sckott, I really appreciate the help!

**Comment by sckott** [comment]
we're supposed to be getting a new version of the Fishbase database, so waiting on that 🕥

**Comment by sckott** [comment]
we have the new version now - should be up soon

**Comment by cboettig** [comment]
```
rfishbase::estimate()
```

is available in the current version.
