### ISSUE TITLE
problem getting correct sciname with SeaLifeBase

### ISSUE THREAD

**Issue by rlrognstad** [ropensci/rfishbase#116]
I’ve been using the FishBase API with no problems, but have noticed some strange behavior with the scientific names when using SeaLifeBase.

As an example, when running the code from the vignette:
```
options(FISHBASE_API` = "http://fishbase.ropensci.org/sealifebase")
kingcrab <- common_to_sci("king crab")
kingcrab
```

returns "Glyptocephalus cynoglossus" (not the correct genus or species). And I get the error
Warning message:
In load_taxa(server = server) :
  Did not recognize API, assuming it is fishbase

However, running
`species(kingcrab)`
seems to return the correct information, including the Genus and Species names, except the entry in “sciname” is wrong.

Am I am missing something about switching the API to SeaLifeBase?  I am running the newest version of rfishbase, updated via “devtools::install_github("ropensci/rfishbase", force = TRUE)” in R 3.3.2

Thanks for your help

**Comment by cboettig** [comment]
Thanks for the report, looks like a bug in `common_to_sci` in which it's passing the SeaLifeBase Species Code to the FishBase lookup table instead.  (King Crab is Limulus polyphemus, which is species code 26 in sealifebase, Glyptocephalus cynoglossus is species code 26 in FishBase.  Should be an easy fix, stand by.

**Comment by rlrognstad** [comment]
Thanks, problem solved.
