### ISSUE TITLE
"Length1" and "Length2" fields switched in Length-Length Table

### ISSUE THREAD

**Issue by flyingmobula** [ropensci/rfishbase#119]
Hi, I was doing some length conversions from SL and FL to TL and I noticed the Length1 and Length2 fields are switched according to the equations provided in the fishbase manual

Length type (2) = a + b × Length type (1)         
Length type (2) = b × Length type (1)

Thank you

**Comment by sckott** [comment]
hi @flyingmobula sorry about the delay. 

What exactly are you talking about?  Is this on the fishbase website, or this package's documentation? or something else?

**Comment by flyingmobula** [comment]
It's okay, thank you for the response. Sorry for not being clear, this issue occurs when I use the rfishbase package and use the length_length() function to retrieve the a and b conversion factors and length1 and length2 fields. For example, I when follow the conversion equations in the fishbase manual and convert from standard length (length1) to total length (length2) using the corresponding a and b factors for a fish species, the converted length actually become shorter, when it should be longer. Length 1 should be Length 2 and vice versa if I were to follow the conversion equation in the fishbase manual.

**Comment by sckott** [comment]
thanks for clarifying. 

in `rfishbase` we only fetch the data from fishbase for you. i don't know anything about the equations. 

any thoughts @cboettig ?

**Comment by cboettig** [comment]
@flyingmobula Good question, I would definitely suggest following up with the fishbase team directly on that, I suppose it's possible they have these switched in the database.  

Have you tried comparing the numbers you're getting here to those shown on the equivalent tables in Fishbase.org?

**Comment by flyingmobula** [comment]
Hi yes, I've checked the length length table on fishbase.org for specific species under where it says more information and the numbers are correct there, except the fields are given as unknown length and known length rather than as length1 and length2. Perhaps an error occurred in renaming the fields? 

If I should contact the fishbase team directly, what would be the best way to contact them? Thanks for all the help.

**Comment by cboettig** [comment]
http://www.fishbase.us/mail/MailForm.php is probably the appropriate choice.

**Comment by flyingmobula** [comment]
Thank you for the reply, I will try contacting them.

**Comment by Dengaloo** [comment]
Hi all
Apologies, my mail system does not copy the thread. What was the concern here?Thanks
Deng

Sent from my iPad

On Jun 20, 2017, at 07:38, flyingmobula <notifications@github.com> wrote:

Thank you for the reply, I will try contacting them.
