### ISSUE TITLE
most functions returning error

### ISSUE THREAD

**Issue by osmarjluiz** [ropensci/rfishbase#120]
I was using rfishbase routinely when out the blue most functions started returning an error. Below are some examples of the errors I'm getting:

> species("Pomacanthus paru")
No encoding supplied: defaulting to UTF-8.
Error in if (parsed$count == 0) { : argument is of length zero
In addition: Warning message:
In check_and_parse(resp) : Internal Server Error (HTTP 500).

> morphometrics("Pomacanthus paru")
No encoding supplied: defaulting to UTF-8.
Error in if (parsed$count == 0) { : argument is of length zero
In addition: Warning message:
In check_and_parse(resp) : Internal Server Error (HTTP 500).

> ecology("Pomacanthus paru")
No encoding supplied: defaulting to UTF-8.
Error in if (parsed$count == 0) { : argument is of length zero

I tried for many other different species but the outcome was the same. Curiously, some other functions , for example species_list, is working fine:

> species_list(Genus="Pomacanthus")
 [1] "Pomacanthus annularis"      "Pomacanthus arcuatus"       "Pomacanthus asfur"          "Pomacanthus chrysurus"     
 [5] "Pomacanthus imperator"      "Pomacanthus maculosus"      "Pomacanthus navarchus"      "Pomacanthus paru"          
 [9] "Pomacanthus rhomboides"     "Pomacanthus semicirculatus" "Pomacanthus sexstriatus"    "Pomacanthus xanthometopon" 
[13] "Pomacanthus zonipectus" 

Any thoughts?

Thanks in advance
Osmar Luiz

**Comment by sckott** [comment]
thanks for the issue. problems with the server - tracking it down now

**Comment by sckott** [comment]
@osmarjluiz  should be working again now.

**Comment by osmarjluiz** [comment]
Working as a charm. Thank you very much!
