### ISSUE TITLE
faoareas function error

### ISSUE THREAD

**Issue by emostarda** [ropensci/rfishbase#123]
Hello,
I tried to extract FAO areas info for all Perciformes: 

```r
# I created the dataset
fish <- species_list(Order = "Perciformes")
fish
# I have 10961 obs. of 3 variables
# I tried to extract FAO Areas info from the first 2000 records
> newdata <- faoareas(fish[1:2000])
# I get the following error
Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "NULL"
In addition: Warning messages:
1: In check_and_parse(resp) : Bad Request (HTTP 400).
2: no results found for query https://fishbase.ropensci.org/faoareas?SpecCode=63845&limit=500&fields=AreaCode%2CSpecCode%2CStatus 
```

I realize that record 63845 (nr 1337) is the problem. so that `> newdata <- faoareas(fish[1:1336])` is working

the next batch works if it starts at `1338 > newdata <- faoareas(fish[1338:2000])` until the next error..

Any idea why?

**Comment by sckott** [comment]
Will have a look, thanks @emostarda

**Comment by sckott** [comment]
was able to reproduce the error - looking into why it happens

**Comment by sckott** [comment]
@emostarda okay, reinstall `devtools::install_github("ropensci/rfishbase")` and try again, 

let me know if it works now

**Comment by emostarda** [comment]
Thanks sckott, it's better now as it doesn't crash, it just excludes a number of rows: 

> Aulopiformes <- species_list(Order = "Aulopiformes")
> AulopAreas <- faoareas(Aulopiformes)
Warning messages:
1: In check_and_parse(resp) : Bad Request (HTTP 400).
2: no results found for query https://fishbase.ropensci.org/faoareas?SpecCode=63598&limit=500&fields=AreaCode%2CSpecCode%2CStatus 
3: In check_and_parse(resp) : Bad Request (HTTP 400).
4: no results found for query https://fishbase.ropensci.org/faoareas?SpecCode=63599&limit=500&fields=AreaCode%2CSpecCode%2CStatus 
5: In check_and_parse(resp) : Bad Request (HTTP 400).
6: no results found for query https://fishbase.ropensci.org/faoareas?SpecCode=64060&limit=500&fields=AreaCode%2CSpecCode%2CStatus
