### ISSUE TITLE
Common_names() does not work for specific species

### ISSUE THREAD

**Issue by jradinger** [ropensci/rfishbase#124]
It seems that common_names() does not work for all species. E.g.
`common_names(species_list=species_list()[6],Language="English")` does not work with `rfishbase_2.1.2`

System:
```
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5
```

This causes also an error when querying mulitple species e.g. `common_names(species_list=species_list()[1:50],Language="English")`

BTW the manual for `common_names()` contains an example using the depreceated `commonnames()`

**Comment by sckott** [comment]
Sorry about delay on this @jradinger 
having a look

**Comment by sckott** [comment]
- [ ] `TW the manual for common_names() contains an example using the depreceated commonnames()`

thanks, fixing now

**Comment by sckott** [comment]
@jradinger fixed, try again after reinstalling `devtools::install_github("ropensci/rfishbase")`

**Comment by wraymond** [comment]
My initial attempt produced the same result. Maybe I did something wrong though. I will try again.

**Comment by sckott** [comment]
@wraymond what did you get?

**Comment by wraymond** [comment]
My apologies, I thought I was responding to another issue.

**Comment by sckott** [comment]
ok
