### ISSUE TITLE
IUCN Redist status?

### ISSUE THREAD

**Issue by MarineKlausi** [ropensci/rfishbase#125]
Thank you for providing this package!
I looked at the documentation and the available fields, but there does not seem to be a way to access the IUCN red list status, correct?
Thanks,
Klaus

**Comment by cboettig** [comment]
We really recommend the redlist API for that, the data is also somewhat more up-to-date.  See https://cran.r-project.org/web/packages/rredlist/index.html

@sckott can comment further when he's back.

**Comment by MarineKlausi** [comment]
Thank you!

**Comment by sckott** [comment]
@MarineKlausi try

```r
install.packages("rredlist")
library(rredlist)
rl_search('Oncorhynchus nerka')$result$category
```
