### ISSUE TITLE
connect with FishLife for life history parameters?

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#129]
Seems like obtaining life-history parameters is a common `rfishbase` use case.  Might be good to point users to @James-Thorson 's [FishLife](https://github.com/James-Thorson/FishLife) (and maybe other packages as well) as a point of comparison to the FishBase numbers?  

Would it be worthwhile getting a sense of how significant the discrepancies are between the two, and maybe discussing with FishBase folk?  (Not my area of expertise, but see https://doi.org/10.1002/eap.1606)

**Comment by James-Thorson** [comment]
I previously found the estimates of life-history parameters from FishBase to be unreliable, but the data from FishBase to be consistent with other data sources (see, http://onlinelibrary.wiley.com/doi/10.1890/12-1855.1/full).  Hence my interest in developing `FishLife`.

I definitely plan to email Rainer Froese and Daniel Pauly to discuss `FishLife` with them and whether its worth integrating its estimates into the FishBase website.  I will definitely keep you in the loop if things go smoothly.

And of course:  thank you for developing `rfishbase`!  It was very helpful.
