### ISSUE TITLE
length_weight function returning incomplete tables

### ISSUE THREAD

**Issue by shaunpwilkinson** [ropensci/rfishbase#130]
Hi there,
I'm using the `length_weight` function to find the _a_ and _b_ parameters for various fish species, but finding that the output tables don't contain all of the entries that appear if I manually navigate to the length-weight table through the fishbase.org user interface. Here's an example:

    Balistapus <- length_weight("Balistapus undulatus") 

This returns a two-row table, with PopLWRef numbers 52323 and 82366. However there are three entries for this species in the table [here](http://www.fishbase.org/popdyn/LWRelationshipList.php?ID=6025&GenusName=Balistapus&SpeciesName=undulatus&fc=445/) including the reference number 108462. This seems to be occurring quite frequently. It's entirely possible that I'm just missing something obvious, in which case I apologize in advance!
Cheers,
Shaun

**Comment by wraymond** [comment]
Hello,
I am having the same issue. When I run my whole list I get a and b values for some species, but after spot checking a few species they have a b values on fish base but are not getting imported. Example:
`length_weight("Pholis laeta")` 

Thanks!

**Comment by sckott** [comment]
@shaunpwilkinson sorry for the delay in response on this 😞 this does work now - we just updated to a March version of the fishbase database, so that's I assume the difference 

```r
length_weight("Balistapus undulatus") %>% 
  dplyr::select(sciname, PopLWRef)
#>                sciname PopLWRef
#> 1 Balistapus undulatus    52323
#> 2 Balistapus undulatus    82366
#> 3 Balistapus undulatus   108462
```

**Comment by sckott** [comment]
@wraymond can you show the page on Fishbase website that shows the data you should be seeing here?

**Comment by wraymond** [comment]
Yeah. http://www.fishbase.org/summary/Pholis-laeta.html. a and b values are under the "Estimates of some properties based on models" heading

**Comment by sckott** [comment]
@wraymond you can see with `Balistapus Ωundulatus` http://www.fishbase.org/summary/Balistapus-undulatus.html that it has a link for a page called `Length-weight` 

<img width="471" alt="screen shot 2017-12-12 at 3 59 07 pm" src="https://user-images.githubusercontent.com/577668/33908192-9628f65e-df55-11e7-9634-363ed5e00d8c.png">

that goes here http://www.fishbase.org/popdyn/LWRelationshipList.php?ID=6025&GenusName=Balistapus&SpeciesName=undulatus&fc=445 and has the data. 

BUT your taxon doesn't have that link/page - so is missing the data in `rfishbase` as well

**Comment by wraymond** [comment]
Ah I see. It makes sense that such a page is required for automated import. So as of now there is no way to import the values in the "Estimates of some properties based on models" fields? 

Thanks

**Comment by sckott** [comment]
we don't scrape their website. so it's a bit misleading perhaps to go from looking at their website to this R package. This package interacts with a dump of the database behind the Fishbase website. It seems that text you want is not in the database, at least not in that database table.
