### ISSUE TITLE
No results or species not found for reproduction function

### ISSUE THREAD

**Issue by fbsut1** [ropensci/rfishbase#131]
Hi, I am trying to gather reproductive info from FishBase. A number of species have Reproduction pages on fishbase.org but the data cannot be called using rfishbase, either because no results could be found (e.g. species [Squalus crassispinus](http://www.fishbase.org/Reproduction/FishReproSummary.php?ID=63433&GenusName=Squalus&SpeciesName=crassispinus&fc=13&stockcode=53546), Allips concolor, Ahlia egmontis) or because the species cannot be found in the database (e.g. species [Coptodon bythobates](http://www.fishbase.org/Reproduction/FishReproSummary.php?ID=10672&GenusName=Coptodon&SpeciesName=bythobates&fc=349&stockcode=10995), Yarica hyalosoma). I tried to reinstall using devtools::install_github("ropensci/rfishbase", force = TRUE) and restarted R, still nothing. 
Any idea why rfishbase cannot access the data for some of these species?
Thanks!
Frieda

**Comment by sckott** [comment]
thanks for the report @fbsut1 

it's possible that the fishbase site is running on a newer version of the underlying data than we are running on. will try to check on that soon

**Comment by fbsut1** [comment]
Hi Scott, I'm not sure that the problem is what you mentioned above (i.e. fishbase site running on newer version), because some of the species and data entries that cannot be found by rfishbase are 10+ years old, and there are more recent entries that are successfully accessed by rfishbase. Anyway, let me know if you come up with anything. Thanks a bunch.

**Comment by sckott** [comment]
okay, thanks

**Comment by sckott** [comment]
@fbsut1 we now support multiple (=3) versions of fishbase database in the API https://github.com/ropensci/fishbaseapi#database-version but we still need to get support here for toggling versions, see https://github.com/ropensci/rfishbase/issues/134, coming soon - looks like this might fix your problem

**Comment by cboettig** [comment]
Hmm, seems all five of these species match fine in the `3.0` version.  

```r
#devtools::install_github("ropensci/rfishbase@3.0")
library(rfishbase)

 species(c("Coptodon bythobates", "Yarica hyalosoma",  "Squalus crassispinus", "Allips concolor", "Ahlia egmontis"))

```


not sure what is up on the current (2.1) version.
