### ISSUE TITLE
Error in retrieving info with validate_names - API down?

### ISSUE THREAD

**Issue by miriamgrace** [ropensci/rfishbase#139]
Hello,

I'm having problems with the validate_names function:
```r
validate_names(c("Oreochromis niloticus", "Salmo trutta"))
```
leads to the error:
```r
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10003 milliseconds
```
I's be grateful for info on this. Thanks!

**Comment by sckott** [comment]
sorry @miriamgrace the server is down again. we are using a non standard server from the university we're at and they have quite a lot of downtime unfortunately, but it is much cheaper than amazon/etc., so there's tradeoffs. we're still working on getting it back up

**Comment by MireiaValle** [comment]
Hi there! How is it going? How long might take since you can fix this issue with the server?
Looking forward to continuing gathering some data! 
Thank you, best wishes and good luck!

**Comment by sckott** [comment]
down again, we should be up on the new server today

**Comment by cboettig** [comment]
Just posting a follow-up on this issue for anyone coming to this thread: please consider upgrading to `rfishbase` v3.0 (just run `update.packages("rfishbase")` to install from CRAN), which now bi-passes the API.  This avoids downtime, improves performance considerably and removes the need to paginate over calls with > 5,000 results.  (Or use any function with no arguments to return all available record for all fish, e.g. `rfishbase::species()`)
