### ISSUE TITLE
Command to access brain weight data from fishbase

### ISSUE THREAD

**Issue by tjquimpo** [ropensci/rfishbase#140]
Dear administrators,

I wonder if there is a way to access the brain weight data in fishbase? Based on the reference by Boettiger and colleagues (2012, 2017), there is currently no means to do that. 

Many thanks,
Tim

**Comment by sckott** [comment]
can you show where you see it in the Fishbase website?

**Comment by tjquimpo** [comment]
On the species page (e.g. after searching for let's say the daisy parrotfish), it is located in the more information section as 'brains'.

**Comment by cboettig** [comment]
@tjquimpo I have an experimental version of this now on the `3.0` branch.  Can you try:

```r
devtools::install_github("ropensci/rfishbase@3.0")
library(rfishbase)

fish <- c("Oreochromis niloticus", "Salmo trutta")
brains(fish)

```

**Comment by cboettig** [comment]
@tjquimpo Sorry for the slow reply here.  

Note that `SL` and `TL` *are* already columns in the brains tables.  If your screen isn't big enough, not all the columns (variables) will be listed.  It might help to select just the columns you need, e.g. 

```r
library(rfishbase)
library(dplyr)

brains() %>% select(Species, BrainWeight, BodyWeight, SL, TL)
```

If you want all only the brains data of a family, say, simply use the `species_list` function to get a list of those species:

```r
species_list(family = "Labridae") %>% 
  brains() %>% 
  select(Species, BrainWeight, BodyWeight, SL, TL)
```

I believe you will find this to be quite fast when using the 3.0 branch :)

**Comment by cboettig** [comment]
(Closing this for now, please re-open if you have any further issues with this.  Also just a note, you can use the `list_fields()` function to help discover other tables that have the desired data.  e.g. the `morphometrics()` table is a good go-to for length and related size information).
