### ISSUE TITLE
How to get the environment  of a specific species ?

### ISSUE THREAD

**Issue by reginaldo-re** [ropensci/rfishbase#141]
I am using rfishbase  * 2.1.2.
I would like to get the environment of a specific species, for example,  Sternarchorhynchus jaimei, (http://www.fishbase.se/summary/65504) ->  Freshwater; demersal.

I tried,  without success:
species_info("Sternarchorhynchus jaimei"), returned Error: could not find function "species_info"
ecology("Sternarchorhynchus jaimei"), returned # A tibble: 0 x 0
stocks("Sternarchorhynchus jaimei"), it does not return the required information
ecosystem("Sternarchorhynchus jaimei"), it does not return the required information 

Thanks, in advance, RR.

**Comment by cboettig** [comment]
Thanks for the issue.  A few quick things to help troubleshoot:

- Note that the function for the `species` table is `species()`, there's no function called `species_info`

If you look on the Fishbase page you link: http://www.fishbase.se/summary/65504, you'll notice that under the heading "More information", most of the tables are greyed-out (no link), including the "Ecology" table.  This is why`ecology("Sternarchorhynchus jaimei")`, returned an empty table.  `rfishbase` cannot return data that is not in fishbase.  

But you should find the "Freshwater", information if you use the `species()` function; see the example in the [package README](https://cran.r-project.org/web/packages/rfishbase/README.html) for more details. Hope this helps, good luck and please let us know

**Comment by reginaldo-re** [comment]
Is it necessary to look to the fields Fresh or Saltwater? What means these two fields?

The field DemersPelag is ok.

thanks,  cboettig, RR.

**Comment by cboettig** [comment]
I believe fishbase uses `-1` to indicate logical TRUE, and 0 as FALSE.  the column called "Comments" often includes a more detailed description of environment as well, useful for humans but not so readable by computers.  (i.e. it observes that "Sea trout" individuals "spend 1 to 5 years in fresh water and 6 months to 5 years in salt water", but also that they can be eaten "microwaved or baked" ....
