### ISSUE TITLE
Validate_names loop over a fish list with errors in output table

### ISSUE THREAD

**Issue by amroco** [ropensci/rfishbase#145]
Hi, Apologies if this is the wrong place to ask this question (just let me know and I can go to Stack),
it's more of a general coding problem, rather than specific to the package.

I would like to apply the validate_names function to a column of species names in a dataframe, and return a dataframe with these columns: 
1. 'Unconfirmed_name' (or the name from my dataset), 
2. 'Valid_name' (the output from the function), and 
3. 'Comment' (the error comment, such as ' FishBase says that 'Fodiator acutus' can also be misapplied to other species but is returning only the best match. See synonyms('Fodiator acutus') for details'). 
If an input name has no result, it would be good to get an NA in the other two columns.

The steps I've taken to try to get at this (although my coding is pretty rudimentary) are to:
1. Get a string of unique names from the dataset to run through the function:
`fish_list = unique(fish_data$species)`
This comes out as a Factor with however many levels, so I make it a list to put it through the function:
`fish_list <- as.list(levels(fish_list))`

2. Create some kind of a loop, which gives me the valid names for each item in the object fish_list, using the validate_names function. I am new to loops, so this is where I know it isn't really a package question, more of a general code question. I am trying to play around with this to start with, but I think my input data is in the wrong format:
`res <- list()
for (i in seq_along(fish_list)) {
  cat(i, sep = "\n")
  res[[i]] <- validate_names(fish_list[i])
}

result = dplyr::bind_rows(res)`

This is probably something simple that I am making hard, and apologies if this isn't the right venue. :[]
 
Thanks,
A

**Comment by cboettig** [comment]
Thanks for getting in touch, this is a fine place to ask questions.  Can you try installing the `3.0` branch from GitHub:

```r
devtools::install_fishbase("ropensci/rfishbase@3.0")
library(rfishbase)
library(dplyr)
```

Then this should be pretty easy, e.g. imagine you have a data frame that includes species names, e.g. like so perhaps (just to illustrate the example): 

```r
df <- species()[1:0, 1:4]
df
```

```
# A tibble: 10 x 4
   SpecCode Species                  SpeciesRefNo Author                   
      <int> <chr>                           <int> <chr>                    
 1        2 Oreochromis niloticus               2 (Linnaeus, 1758)         
 2        3 Oreochromis mossambicus             1 (Peters, 1852)           
 3        4 Engraulis ringens                 189 Jenyns, 1842             
 4        5 Orthopristis chrysoptera           25 (Linnaeus, 1766)         
 5        6 Coryphaena hippurus                26 Linnaeus, 1758           
 6        7 Coryphaena equiselis               26 Linnaeus, 1758           
...
```

Almost all `rfishbase` functions operate on a list (character vector) of species names, rather than a data.frame, so you'll want to pull out just that column.  The data you want is in the synonyms table, e.g.

```r
df %>% pull(Species) %>% synonyms()
```

```
                    synonym            Status SpecCode SynCode CoL_ID    TSN WoRMS_ID ZooBank_ID TaxonLevel                  Species
1     Oreochromis niloticus     accepted name        2   58305   <NA> 553310       NA       <NA>    Species    Oreochromis niloticus
2   Oreochromis mossambicus     accepted name        3   22699   <NA> 170015       NA       <NA>    Species  Oreochromis mossambicus
3         Engraulis ringens     accepted name        4   29372   <NA> 551340   272287       <NA>    Species        Engraulis ringens
4  Orthopristis chrysoptera     accepted name        5   22701   <NA> 169077   158810       <NA>    Species Orthopristis chrysoptera
5       Coryphaena hippurus     accepted name        6   22215   <NA> 168791   126846       <NA>    Species      Coryphaena hippurus
6      Coryphaena equiselis     accepted name        7   29358   <NA> 168792   126845       <NA>    Species     Coryphaena equiselis
7       Abalistes stellaris     accepted name        9   53544   <NA> 646167   219872       <NA>    Species      Abalistes stellaris
8       Abalistes stellaris   misapplied name    62612  156673   <NA>     NA       NA       <NA>    Species   Abalistes filamentosus
9            Alectis indica     accepted name       10    8344   <NA> 642015   401562       <NA>    Species           Alectis indica
10           Alectis indica ambiguous synonym      988   60765   <NA>     NA   302283       <NA>    Species         Alectis ciliaris
11  Cephalopholis cruentata     accepted name       12   22703   <NA> 181220   279146       <NA>    Species  Cephalopholis cruentata
12 Epinephelus adscensionis     accepted name       14   22704   <NA> 167696   159351       <NA>    Species Epinephelus adscensionis
```

(Scroll right for all the data).  The provided name is in the synonym column, the "Comment" is the Status column, and the valid recognized name in Fishbase is in the Species column.  You can of course just select (and rename) these columns if you don't want all that other data:

```r
df %>% pull(Species) %>% synonyms() %>%
 select(provided_name = synonym, valid_name = Species, Comment = Status) 

> df %>% pull(Species) %>% synonyms() %>%
+     select(provided_name = synonym, valid_name = Species, Comment = Status) 
              provided_name               valid_name           Comment
1     Oreochromis niloticus    Oreochromis niloticus     accepted name
2   Oreochromis mossambicus  Oreochromis mossambicus     accepted name
3         Engraulis ringens        Engraulis ringens     accepted name
4  Orthopristis chrysoptera Orthopristis chrysoptera     accepted name
5       Coryphaena hippurus      Coryphaena hippurus     accepted name
6      Coryphaena equiselis     Coryphaena equiselis     accepted name
7       Abalistes stellaris      Abalistes stellaris     accepted name
8       Abalistes stellaris   Abalistes filamentosus   misapplied name
9            Alectis indica           Alectis indica     accepted name
10           Alectis indica         Alectis ciliaris ambiguous synonym
11  Cephalopholis cruentata  Cephalopholis cruentata     accepted name
12 Epinephelus adscensionis Epinephelus adscensionis     accepted name
```


Note how two names in my example are listed as both "accepted name" and also "ambiguous synonym" or "misapplied name" to another species, hence the results include 12 rows instead of the original 10, with these two cases each listed separately.

**Comment by cboettig** [comment]
closing for now, please re-open if you have any issue with this.  bug reports and questions always welcome, it helps us better understand what our users are looking for!

**Comment by amroco** [comment]
Awesome, that is exactly what I am after and a simpler process! 
But I am unfortunately not getting the same table. 

Let's say I have a dataset like so:

```
# mock-up data
test.data = data.frame(Location=sample(c("Sydney", "Solitary Islands", "Montague Island"),100, TRUE),
                       Life_stage=sample(c("Juvenile", "Adult"), 100, TRUE),
                       species=sample(c("Odax cyanomelas", 
                                  "Dinolestes lewini", 
                                  "Thalassoma lunare",
                                  "Hime purpurissatus",
                                  "Atypichthys strigatu",
                                  "Chaetodon citrinellus"), 100, TRUE))
str(test.data)

test_fish_list = unique(test.data$Species)
test_fish_list
is.vector(test_fish_list)
```

I want to get just the unique species out of this list, so I do the following:

`    fish_list = unique(test.data$species)`

The resulting output is a character vector, so I run this through the synonyms query:
`devtools::install_fishbase("ropensci/rfishbase@3.0")
library(rfishbase)`

`     result = synonyms(test_fish_list)`

But, the result I am getting looks different to yours. I can't see the input species column:

   ```
> result
# A tibble: 5 x 12
  SynCode SpecCode SynGenus SynSpecies Status Valid Synonymy Combination
    <int>    <int> <chr>    <chr>      <chr>  <lgl> <chr>    <chr>      
1   28643    12839 Odax     cyanomelas synon~ FALSE senior ~ new combin~
2   25735     5645 Thalass~ lunare     accep~ TRUE  senior ~ new combin~
3  135996    14021 Hime     purpuriss~ synon~ FALSE senior ~ new combin~
4   25063     4332 Dinoles~ lewini     accep~ TRUE  senior ~ new combin~
5   31431     5561 Chaetod~ citrinell~ accep~ TRUE  senior ~ original c~
# ... with 4 more variables: Misspelling <lgl>, CoL_ID <lgl>, TSN <int>,
#   WoRMS_ID <int>
```

So where I am getting FALSE I should be getting alternatives, and I should have that column where my input species name is. Do you think somethings up and that I still have an older rFishbase version?
I intentionally left the final 's' off of 'Atypichthys strigatu' to see whether the query could pick up on something like that (a spelling error) but it is okay if it doesn't - because an NA is still a result and it flags that something is going on with that species name, and would make us look closer at it. :)

Eventually I want to use this code to check and ensure the entire species lists of other databases, with thousands of species, are up-to-date according to what fishbase has. :)

Thanks so much!
