### ISSUE TITLE
distribution range coordinates

### ISSUE THREAD

**Issue by guido167** [ropensci/rfishbase#148]
Is it still possible with rfishbase 3.0 to pull the coordinates of the range of a species? When I use:
`distribution("Carcharhinus limbatus", fields= c("NorthernLatitude", 
                                                  "NorthernLatitudeNS", 
                                                  "SouthernLatitude", 
                                                  "SouthernLatitudeNS"))`

This only returns AreaCodes and FAO regions. Thank you!

**Comment by manchih** [comment]
Hi
That's exactly what I've been looking for since yesterday. As an alternative, I wanted to use the table "occurrence" to take the max and min of PointData but it does'nt work.
Still searching...

**Comment by cboettig** [comment]
Thanks much for reporting this, should be fixed now.  can you install the github version again and test it out and let us know how it goes?  

(also listing `fields` should actually do the filter for you this time; omit it to see the full table).

**Comment by guido167** [comment]
Works now! Thanks for fixing this on such a short notice!

**Comment by cboettig** [comment]
yay, thanks for confirming. We really appreciate the 🐞 reports!

**Comment by manchih** [comment]
Hi,
Thank you for your quick response,
The "NorthernLatitude" and "SouthernLatitude" seems to be the limits for the FAO region where the species occure.
I'm searching for the information displayed in the "Distribution range" in the web version of fishbase: Exemple: 45°N - 38°S, 180°W - 180°E; in the case of Carcharhinus limbatus.
Sincerely.

**Comment by cboettig** [comment]
thanks for checking this.  Correct, `distribution()` is returning the fao area information.  It's really not clear to me where that information is coming from.   rfishbase queries the tables from the backend database directly, and so it's not always intuitive which table the fishbase web version uses for any particular value.  

There isn't a "distribution" table, and there isn't an "occurrence" table any more, though there used to be historically.  It has to be in there somewhere but we will need to do some more reverse engineering to figure out where...  

feel free to dig around as well, you can access most of the tables directly from the recently created Zenodo archive; this is effectively what the 3.0 version of rfishbase is doing internally  as well: https://zenodo.org/badge/latestdoi/148454670
