### ISSUE TITLE
Species Codes and the synonyms() function

### ISSUE THREAD

**Issue by TIGibson** [ropensci/rfishbase#150]
Hi, 

I am experiencing an issue with the synonyms() function. Specifically it does not appear to accept Species Codes. This change appears to have happened in the last week. This may have been to do with rfishbase 3.0 going up on CRAN (I think I was using the previous version when I got it working)? I am trying to download large numbers of synonyms for species of interest for a bioinformatics project I am undertaking so any support would be useful.  

Worked Example

```r
# 13/11/2018
# Tom Gibson
# Example of Species List Issue

# Install packages
install.packages("rfishbase")

library("rfishbase")
library("dplyr")

# create vector

fsh <- c("Agonus cataphractus", "Alburnus alburnus", "Alosa alosa", "Alosa fallax") # write in names
fsh_val <- validate_names(fsh) # validate names
fsh_code <- species(fsh_val, fields = "SpecCode") # get species codes

synonyms(species_list = fsh_code$SpecCode) # get the synonyms from the codes
# Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
#   Can't join on 'synonym' x 'synonym' because of incompatible types (character / integer)

# Does the above work when scientific names are used?
synonyms(species_list = fsh) # yes
#               synonym        Status SpecCode SynCode CoL_ID    TSN WoRMS_ID ZooBank_ID TaxonLevel             Species
# 1 Agonus cataphractus accepted name       36   22710   <NA> 167454   127190       <NA>    Species Agonus cataphractus
# 2   Alburnus alburnus accepted name     4730   25279   <NA> 163663       NA       <NA>    Species   Alburnus alburnus
# 3         Alosa alosa accepted name      101   22770   <NA> 161708   126413       <NA>    Species         Alosa alosa
# 4        Alosa fallax accepted name     5355   25577   <NA> 161716   126415       <NA>    Species        Alosa fallax

# Is the error given for individual codes?
synonyms(36) # yes
# Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
# Can't join on 'synonym' x 'synonym' because of incompatible types (character / numeric)

```

**Comment by TIGibson** [comment]
Hi Carl,

Thanks for the work around, will give it a go tomorrow.

Also thanks for the work on this package more widely! It’s a life saver.

Kind Regards,

Tom
________________________________

**Comment by cboettig** [comment]
Closing this out as I think we have resolved it now?  Given the nature of the synonyms table, it's not obvious that it should take a list of only accepted species names or species codes, probably easier to work with using the whole table as outlined above.

**Comment by TIGibson** [comment]
Hi Carl,

Yes thanks for this.

Kind Regards,

Tom
