### ISSUE TITLE
Missing species SpecCode

### ISSUE THREAD

**Issue by MDumestre** [ropensci/rfishbase#151]
Hello, 

Thank you first for the new rfishbase package!
I wonder why a species like "Eviota lateritea" or "Parascombrops madagascariensis" has no specific SpecCode, while it has a FishBase page?
>species("Eviota lateritea", fields=("SpecCode")) 
>species("Parascombrops madagascariensis", fields=("SpecCode"))

Btw, would it be possible to have access to the species SynCode, this code only appears in the Synonyms function?

Thank you for your help, 
Marielle

**Comment by cboettig** [comment]
@MDumestre Looks like these are two very recently described species that are not yet in the FishBase database dump we use on the backend, (hence no SpecCode or anything else).  

Note that you can always easily join tables to get the columns you want.  e.g. try:

```r
library(dplyr)
species() %>% 
  left_join(synonyms()) %>% 
  select(SpecCode, Species,  SynCode, synonym, Status) 
```

(note in 3.0 you can omit any argument to the functions to get all available records).
