### ISSUE TITLE
rfishbase timeout

### ISSUE THREAD

**Issue by kleisner** [ropensci/rfishbase#152]
Hi, I'm trying to query rfishbase and any command I use (validate_names, mat, etc.) gives me the following error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10016 milliseconds

Is there an issue with the fishbase servers at this time?

**Comment by sckott** [comment]
it's down again. we should be on the new server today hopefully

**Comment by cboettig** [comment]
@kleisner Can you also let us know which version of `rfishbase` you are using?  If you `update.packages("rfishbase")`, you should find the newer version is much faster and will bypass the API to use a local cache.

**Comment by kleisner** [comment]
Great thanks for the info! 
@cboettig I'm using 2.1.2. I just ran the update.packages, but looks like it's the latest version?

**Comment by cboettig** [comment]
that's strange.  should be 3.0.0.  (e.g. https://cran.r-project.org/web/packages/rfishbase/index.html).  Did you restart R after installing the package?  

If restarting does not fix it, can you try:  

```
install.packages("rfishbase", repo = "http://cran.rstudio.com")
```

and see if that works?

**Comment by kleisner** [comment]
Hi--yes, I had restarted to see if that updated the package version, but it was still 2.1.2. I ended up removing the package and just reinstalling and that worked! The rfishbase functions are also now working. Thank you!

**Comment by cboettig** [comment]
🎉
