### ISSUE TITLE
missing trophic level data?

### ISSUE THREAD

**Issue by andybeet** [ropensci/rfishbase#154]
I have recently been using rfishbase to extract the trophic level (field = DietTroph) for a set of species.

For some of the species i find that the DietTroph field has NA as its value.

However, if i search the online fishbase database, i find a value.

For example:

rfishbase::ecology("Anchoa mitchilli",fields="DietTroph",server="fishbase")

returns an NA where as on line (https://www.fishbase.de/summary/Anchoa-mitchilli.html) the value is 3.5

I find this occurring for 34 of the 280 species i have searched for.

Are you aware of this? Thanks

**Comment by cboettig** [comment]
Yeah, FishBase is not particularly organized or transparent about where different data comes from in the different tables.  Short answer is you probably wanted FoodTroph:

    library(tidyverse)
    library(rfishbase)
    ecology("Anchoa mitchilli") %>% select(FoodTroph)

It can be helpful to go directly to the ecology page to get a better comparison to the `ecology()` table you are using there, e.g. https://www.fishbase.de/Ecology/FishEcologySummary.php?StockCode=561&GenusName=Anchoa&SpeciesName=mitchilli, but it is still a lot of guess work to match up fields, which seem to have duplicates and variation.  e.g. you're probably also aware there is also a Diet table, e.g. https://www.fishbase.de/TrophicEco/DietCompoList.php?ID=545&GenusName=Anchoa&SpeciesName=mitchilli&fc=454&StockCode=561 or in R: 

    rfishbase::diet("Anchoa mitchilli") 

which gives a range of samples, with citations (which notably do not average to 3.5; though as you can see from the references linked in the table on the ecology page (or in the returned data.frame, but not on the Species landing page), these come from two different references.  

HTH

**Comment by andybeet** [comment]
Thanks Carl,
I have a further question. Take for example The species "Naucrates ductor" (Pilotfish)

rfishbase::diet("Naucrates ductor")["Troph"] gives NA
rfishbase::ecology("Naucrates ductor",fields ="FoodTroph",server="fishbase") gives 3.98
rfishbase::ecology("Naucrates ductor",fields ="DietTroph",server="fishbase") gives NA
but online (https://www.fishbase.de/summary/Naucrates-ductor.html) gives 3.4.

So it appears that this value of 3.4 is stored somewhere else in fishbase (a 4th location!)

Any ideas? 

I am writing code to obtain the trophic level for a list of species. Not knowing where the data is stored is quite a problem!! 
cheers

**Comment by andybeet** [comment]
A further question regarding an invertibrate species in sealifebase also relating to trophic level
The species "Strongylocentrotus droebachiensis" (Northern sea urchin) has an "estimated" trophic level of 2.4. 
See (https://www.sealifebase.org/Ecology/FishEcologySummary.php?StockCode=4199&GenusName=Strongylocentrotus&SpeciesName=droebachiensis)

i can not seem to obtain this value using rfishbase

rfishbase::estimate("Strongylocentrotus droebachiensis",server="sealifebase") (All fields are NA's)
rfishbase::ecology("Strongylocentrotus droebachiensis",fields="FoodTroph",server="sealifebase")
rfishbase::ecology("Strongylocentrotus droebachiensis",fields="DietTroph",server="sealifebase")
rfishbase::diet("Strongylocentrotus droebachiensis",server="sealifebase")["Troph"]

All of these locations return NA's

Am i missing something?
Thanks again

**Comment by cboettig** [comment]
Hi Andy, 

Sorry I don't have good answers for the missing data -- rfishbase is using the October 2018 dumps from SLB and FB that we have and exposing those tables.  As you've seen, sometimes it's just a matter of figuring out which table the website is using for a particular number, some are more obvious than others.  Meanwhile closing this out since this doesn't appear to be an actionable bug from our end, the functions return the data from the tables we have available.

**Comment by andybeet** [comment]
Hi Carl,

So i checked with the folks at fishbase (sealifebase) and the value of trophic level (2.4) for the species i mentioned above (Strongylocentrotus droebachiensis) has been in the data base since 2011. And it resides in one of the tables that rfishbase extracts data from.

With all due respect, a user of rfishbase is expecting that he/she will be able to pull the data he/she sees online. If that doesn't happen for whatever reason, trust in the software is seriously diminished. I hope you have time to find a resolution to this since this does seem to be an implementation error.

thanks
Andy

**Comment by cboettig** [comment]
Hi Andy,

Sorry about this, looks the sealifebase functions were not always getting the `server` argument to use the right SpecCode column, and hence not finding the names.  Try:

```
remotes::install_github("ropensci/rfishbase")
library(rfishbase)
library(dplyr)


ecology("Strongylocentrotus droebachiensis", server = "sealifebase") %>% select(dplyr::matches("Troph"))
```

I think that should have what you are looking for.  


Didn't mean to be dismissive of the issue earlier, but you know this line of work I'm paid to write papers; supporting software is just time away from that.  Anyway, thanks for the bug report.

**Comment by andybeet** [comment]
All fields have NA's. The same for the estimate table
None of the fields have the value of 2.4 which is meant to reside in one of these tables.

I hear you regarding doing research and not supporting software. Doesn't help me though ;)

**Comment by cboettig** [comment]
Hi Andy,

Are you sure you re-installed the package and restarted your R instance?  I see 2.4 right there now:

![Screen Shot 2019-03-21 at 11 14 44 AM](https://user-images.githubusercontent.com/222586/54775183-a548cf00-4bca-11e9-8008-72c1cb4c5b8a.png)

**Comment by andybeet** [comment]
i didn't reinstall!!
Now i have, and you are right. Thanks a million. Get back to writing papers ;)
