### ISSUE TITLE
Access "Species Ecology Matrix" through rfishbase

### ISSUE THREAD

**Issue by BenMFord** [ropensci/rfishbase#169]
Hello,

Is there a way to access the FishBase "Species Ecology Matrix"  through rfishbase?

i.e. for Scarids - https://www.fishbase.se/report/KeyFactsMatrixList.php?famcode=364

Thanks

**Comment by sckott** [comment]
looks like the `/matrix` API route has that data e.g. https://fishbase.ropensci.org/matrix/?SpecCode=5537 - but we don't have a fxn for that in this pkg @cboettig - should we add a fxn for matrix?

**Comment by cboettig** [comment]
@sckott good call.  Meanwhile, users can generate the endpoint automatically with the internal `endpoint` function factory:

e.g.

```r
ecology_matrix <- rfishbase:::endpoint("matrix")
ecology_matrix()
```

**Comment by sckott** [comment]
nice one, had forgotten about that

**Comment by BenMFord** [comment]
Thank you very much!
