### ISSUE TITLE
species function does not call estimates based on models

### ISSUE THREAD

**Issue by corinthiablack** [ropensci/rfishbase#172]
When using the species function, I was unable to call "Preferred Temperature" and "Trophic Level" in the table.

<details> <summary><strong>Session Info</strong></summary>

```r
example=species("Parophrys vetulus")
```
</details>

**Comment by cboettig** [comment]
Apologies, but rfishbase merely accesses the back-end database tables, whose organization is not always intuitive.  For temperature and related data, please consider using the `ecosystem()` function.  Trophic information is available in the `ecology()` function, and several others, as noted if you do a search of the issues here.
