### ISSUE TITLE
"Type" column of common_names table

### ISSUE THREAD

**Issue by JulietteLgls** [ropensci/rfishbase#175]
Hello, 
I just loaded the last version of rfishbase and I wonder if there is any way to get the column "Type" from the common name table available on the website throught the function common_names?
Actually what I'd like to get is the common name of wo-hich type if FAO or AFS.

Thanks in advance.
Juliette

**Comment by cboettig** [comment]
Apologies for the slow reply.  

Try 

```r
rfishbase:::fb_tbl("comnames")
```

and look at the `NameType` column.  Apologies this data isn't exposed directly; we'll try and address it in the next release!

**Comment by JulietteLgls** [comment]
Sorry, forgot to reply, thank you, I close the issue
