### ISSUE TITLE
add rfishbase as a conda environment with Anaconda cloud

### ISSUE THREAD

**Issue by Grelot** [ropensci/rfishbase#178]
Hi, Thanks a lot for your awesome package,

I want to start a new project using R/jupyter notebook and i need to install my R packages with conda.

I checked for `rfishbase` availability but it seems to not be present (perhaps i'm wrong)

https://anaconda.org/search?q=rfishbase

Is `rfishbase` available as a R package you can install using conda ?

**Comment by sckott** [comment]
I'm not familiar with how R pkgs get into conda. Are you?

**Comment by cboettig** [comment]
cc @choldgraf might have suggestions (either on R/jupyter notebook sans conda or getting packages listed with conda?)

**Comment by Grelot** [comment]
The best will be to find it on anaconda/miniconda cloud

Here the link: 
https://anaconda.org/peguerin/dashboard

Apparently the process seems to be pretty straightforward

**Comment by choldgraf** [comment]
Hey all - sorry for the slow response, I've been out of the country for the last two weeks. For conda, your best bet is to use `conda-forge`, which is a community-driven channel of the `conda` tool (https://conda-forge.org/). I'm not familiar with how to publish on it, but I've found the developer community in conda-forge to be pretty responsive so perhaps they can help out
