### ISSUE TITLE
Access to species temperature tolerance range data

### ISSUE THREAD

**Issue by jatalah** [ropensci/rfishbase#180]
Hi,

Is there a way to access the species temperature range using rfishbase?

This info appears on the Environment section on the main page for each species in FishBase.

For example: 
Environment: milieu / climate zone / depth range / distribution rangeEcology
Freshwater; brackish; benthopelagic; potamodromous (Ref. 51243); depth range 0 - 20 m (Ref. 32849), usually ? - 20 m (Ref. 34290).   Tropical; **14°C - 33°C** (Ref. 3); 32°N - 5°S, 17°W - 38°E

Cheers,
J

**Comment by cboettig** [comment]
Try the `environment()` table?  Usually the rfishbase function names match the FishBase page names, though sometimes it just takes some poking around.  see https://github.com/ropensci/rfishbase#fishbase-docs-discovering-data
