### ISSUE TITLE
data_frame function should be replaced

### ISSUE THREAD

**Issue by kdgorospe** [ropensci/rfishbase#184]
This is not really a bug report, but probably something you should be aware of. I'm using the function rfishbase::synonyms, and although it works fine, I get the following warning message from R: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.

**Comment by sckott** [comment]
thanks! you're welcome to send a pull request, or we'll get to it soon

**Comment by sckott** [comment]
@kdgorospe  i can't replicate the issue - please share your session info

**Comment by kdgorospe** [comment]
Sure! Here's my session info, along with the warning message when I run the
rfishbase's synonyms function (but executed within another function):

`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.This warning is displayed once every 8
hours.Call `lifecycle::last_warnings()` to see where this warning was
generated.> sessionInfo()R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
LC_ADDRESS=C               LC_TELEPHONE=C
LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] roxygen2_7.1.0    data.table_1.12.8 rfishbase_3.0.4
forcats_0.5.0     stringr_1.4.0     dplyr_0.8.5       purrr_0.3.4
 readr_1.3.1       tidyr_1.0.3
[10] tibble_3.0.1      ggplot2_3.3.0     tidyverse_1.3.0   speciesnet_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     lubridate_1.7.8  ape_5.3
lattice_0.20-41  zoo_1.8-8        foreach_1.5.0    assertthat_0.2.1
digest_0.6.25    packrat_0.5.0    plyr_1.8.6
[11] R6_2.4.1         cellranger_1.1.0 backports_1.1.6  reprex_0.3.0
  httr_1.4.1       pillar_1.4.4     rlang_0.4.6      curl_4.3
readxl_1.3.1     rstudioapi_0.11
[21] taxize_0.9.95    urltools_1.7.3   triebeard_0.3.0  munsell_0.5.0
  broom_0.5.6      compiler_3.6.3   modelr_0.1.7     xfun_0.13
pkgconfig_2.0.3  tidyselect_1.0.0
[31] httpcode_0.3.0   lpSolve_5.6.15   codetools_0.2-16 reshape_0.8.8
  fansi_0.4.1      crayon_1.3.4     dbplyr_1.4.3     withr_2.2.0
crul_0.9.0       grid_3.6.3
[41] nlme_3.1-147     jsonlite_1.6.1   gtable_0.3.0
lifecycle_0.2.0  DBI_1.1.0        magrittr_1.5     scales_1.1.0
cli_2.0.2        stringi_1.4.6    fs_1.4.1
[51] xml2_1.3.2       ellipsis_0.3.0   generics_0.0.2   vctrs_0.2.4
  gh_1.1.0         iterators_1.0.12 tools_3.6.3      bold_0.9.0
glue_1.4.0       hms_0.5.3
[61] parallel_3.6.3   colorspace_1.4-1 rvest_0.3.5      memoise_1.1.0
  knitr_1.28       haven_2.2.0

**Comment by sckott** [comment]
thanks, i think we fixed this in the dev version, install it  `remotes::install_github("ropensci/rfishbase")` and try again

**Comment by kdgorospe** [comment]
Hi Scott,

Yup problem fixed! Sorry, I didn't even consider trying the dev version.
Thanks!
