### ISSUE TITLE
connect_db?

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#185]
@cboettig was running check on this pkg locally, and there's an error in running examples b/c `connect_db` fxn is not found https://github.com/ropensci/rfishbase/blob/master/R/local_db.R#L92 any ideas?

**Comment by cboettig** [comment]
Whoops, that should say `default_db()`  (renamed the fn and forgot to update the example!)

**Comment by cboettig** [comment]
(reason for renaming this was to suggest that it really was just a 'default', since you can BYO database connection object instead of using that one.  `default_db()` just exists to select a good DB automatically if available.

**Comment by sckott** [comment]
ok, thx
