### ISSUE TITLE
validate_names introduces NAs

### ISSUE THREAD

**Issue by neuscamllo** [ropensci/rfishbase#186]
Hi everyone,

When I add a new species list of 28 entries and validate their names with validate_names() function I end up with 38 entries. Some of the names have been updated as wexpected, but the function added 10 NAs sparseley within the list. I can potentially remove them but I'm just wondering why is it doing this and if it might bring some unexpected trouble when I apply this to a larger dataset (100s of entries).

     t <- c("Argyropelecus hemigymnus","Benthalbella infans","Benthocometes robustus","Benthosema glaciale", "Bolinichthys indicus","Bonapartia pedaliota","Capros aper","Chauliodus danae","Chauliodus sloani", "Chlopsis bicolor","Cyclothone braueri","Cyclothone microdon","Diaphus holti","Diaphus rafinesquii", "Gonostoma elongatum","Hygophum hygomii","Idiacanthus fasciola","Lampanyctus pusillus","Lepidophanes guentheri", "Lobianchia dofleini","Macroramphosus scolopax","Myctophum punctatum","Notolychnus valdiviae","Notoscopelus bolini", "Stomias boa","Valenciennellus tripunctulatus","Vinciguerria poweriae","Xenodermichthys copei")

t2<-validate_names(t)
[1] "Argyropelecus hemigymnus"       "Benthalbella infans"            "Benthocometes robustus"        
 [4] "Benthosema glaciale"            "Bolinichthys indicus"           "Bonapartia pedaliota"          
 [7] "Capros aper"                    "Chauliodus danae"               NA                              
[10] "Chauliodus sloani"              NA                               NA                              
[13] "Chlopsis bicolor"               "Cyclothone braueri"             "Cyclothone microdon"           
[16] NA                               "Diaphus holti"                  NA                              
[19] "Diaphus rafinesquii"            NA                               "Sigmops elongatus"             
[22] "Hygophum hygomii"               NA                               "Idiacanthus fasciola"          
[25] NA                               "Lampanyctus pusillus"           "Lepidophanes guentheri"        
[28] "Lobianchia dofleini"            "Macroramphosus scolopax"        "Myctophum punctatum"           
[31] "Notolychnus valdiviae"          "Notoscopelus bolini"            NA                              
[34] "Stomias boa boa"                "Valenciennellus tripunctulatus" NA                              
[37] "Vinciguerria poweriae"          "Xenodermichthys copei"         

Thanks,

**Comment by amuel97** [comment]
I am having the same issue and can't figure it out!

**Comment by sckott** [comment]
thanks @neuscamllo and @amuel97 - I'll have a look

**Comment by sckott** [comment]
@neuscamllo @amuel97 can you restart R, reinstall `remotes::install_github("ropensci/rfishbase")`,  and try again

```r
x <- c("Argyropelecus hemigymnus","Benthalbella infans","Benthocometes robustus",
  "Benthosema glaciale", "Bolinichthys indicus","Bonapartia pedaliota",
  "Capros aper","Chauliodus danae","Chauliodus sloani", "Chlopsis bicolor",
  "Cyclothone braueri","Cyclothone microdon","Diaphus holti","Diaphus rafinesquii", 
  "Gonostoma elongatum","Hygophum hygomii","Idiacanthus fasciola","Lampanyctus pusillus",
  "Lepidophanes guentheri", "Lobianchia dofleini","Macroramphosus scolopax",
  "Myctophum punctatum","Notolychnus valdiviae","Notoscopelus bolini", "Stomias boa",
  "Valenciennellus tripunctulatus","Vinciguerria poweriae","Xenodermichthys copei")
res = validate_names(x)
data.frame(original = x, new = res, same = x==res)
#>                          original                            new  same
#> 1        Argyropelecus hemigymnus       Argyropelecus hemigymnus  TRUE
#> 2             Benthalbella infans            Benthalbella infans  TRUE
#> 3          Benthocometes robustus         Benthocometes robustus  TRUE
#> 4             Benthosema glaciale            Benthosema glaciale  TRUE
#> 5            Bolinichthys indicus           Bolinichthys indicus  TRUE
#> 6            Bonapartia pedaliota           Bonapartia pedaliota  TRUE
#> 7                     Capros aper                    Capros aper  TRUE
#> 8                Chauliodus danae               Chauliodus danae  TRUE
#> 9               Chauliodus sloani              Chauliodus sloani  TRUE
#> 10               Chlopsis bicolor               Chlopsis bicolor  TRUE
#> 11             Cyclothone braueri             Cyclothone braueri  TRUE
#> 12            Cyclothone microdon            Cyclothone microdon  TRUE
#> 13                  Diaphus holti                  Diaphus holti  TRUE
#> 14            Diaphus rafinesquii            Diaphus rafinesquii  TRUE
#> 15            Gonostoma elongatum              Sigmops elongatus FALSE
#> 16               Hygophum hygomii               Hygophum hygomii  TRUE
#> 17           Idiacanthus fasciola           Idiacanthus fasciola  TRUE
#> 18           Lampanyctus pusillus           Lampanyctus pusillus  TRUE
#> 19         Lepidophanes guentheri         Lepidophanes guentheri  TRUE
#> 20            Lobianchia dofleini            Lobianchia dofleini  TRUE
#> 21        Macroramphosus scolopax        Macroramphosus scolopax  TRUE
#> 22            Myctophum punctatum            Myctophum punctatum  TRUE
#> 23          Notolychnus valdiviae          Notolychnus valdiviae  TRUE
#> 24            Notoscopelus bolini            Notoscopelus bolini  TRUE
#> 25                    Stomias boa                Stomias boa boa FALSE
#> 26 Valenciennellus tripunctulatus Valenciennellus tripunctulatus  TRUE
#> 27          Vinciguerria poweriae          Vinciguerria poweriae  TRUE
#> 28          Xenodermichthys copei          Xenodermichthys copei  TRUE
```

**Comment by amuel97** [comment]
That worked for me! Thank you!

**Comment by neuscamllo** [comment]
Thanks @sckott, that worked as well for me! what was the issue?

**Comment by sckott** [comment]
https://github.com/ropensci/rfishbase/commit/1ed74812f504315b473d2fe14abd73fdb43d51a8?w=1#diff-a832126930ce55f66a0d6d951574232eR88-R91

We needed to group by taxon and then filter out NAs

**Comment by neuscamllo** [comment]
Great, thanks!
