### ISSUE TITLE
swim bladders

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#188]
someone asked about this. there's swim bladder data in the database tables:

- larvae: maps to speccode so you can query on a species to get to the data. was already present in the API and there's a fxn in rfishbase already
    - e.g., https://fishbase.ropensci.org/larvae/
- disref: wasn't in the API yet, added now. but no function in rfishbase. doesn't map to species as far as i can tell. but DisCode is in disref table, which can be mapped to dispic or diseases tables which do have speccode so can be mapped to species. not sure how to approach this
    - e.g., https://fishbase.ropensci.org/disref/

**Comment by sckott** [comment]
cc @erinann

**Comment by sckott** [comment]
@cboettig okay if we add a fxn in the pkg for disref?  any thoughts on swim bladder data in fishbase? have you ever used it?

**Comment by erinann** [comment]
@sckott, thanks for getting this started. 

I've been playing with the larvae table and there are duplicates (a couple conflicting duplicates too) for a few of the species I'm looking at. Is this something `rfishbase` maintainers need to know about or something with FishBase should deal with?


```r
fish_gasbladder <- larvae(c("Brama brama", "Clupea harengus", 
                            "Arctozenus risso", "Etrumeus sadina"),
                          fields = c("SpecCode", "Species", "GasBladderEarly",
                                                "GasBladderLate"))
```
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> SpecCode </th>
   <th style="text-align:left;"> Species </th>
   <th style="text-align:left;"> GasBladderEarly </th>
   <th style="text-align:left;"> GasBladderLate </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 391 </td>
   <td style="text-align:left;"> Brama brama </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 391 </td>
   <td style="text-align:left;"> Brama brama </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;"> Clupea harengus </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:left;"> Clupea harengus </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 6977 </td>
   <td style="text-align:left;"> Arctozenus risso </td>
   <td style="text-align:left;"> absent </td>
   <td style="text-align:left;"> absent </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 6977 </td>
   <td style="text-align:left;"> Arctozenus risso </td>
   <td style="text-align:left;"> invisible </td>
   <td style="text-align:left;"> invisible </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1455 </td>
   <td style="text-align:left;"> Etrumeus sadina </td>
   <td style="text-align:left;"> visible </td>
   <td style="text-align:left;"> visible </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1455 </td>
   <td style="text-align:left;"> Etrumeus sadina </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
</tbody>
</table>

**Comment by sckott** [comment]
thanks @erinann  We only get a copy of the data from Fishbase - so definitely the duplicates should be addressed to them. I've asked and will let you know what the response is.

**Comment by sckott** [comment]
@erinann  heard back from them. does this help?

> there can be more than one entry in the larvae table for a given species. It either pertains to the record for a certain population of the species (e.g. speccode 24, Clupea harengus). or record for the area it was reported based on the reference used (termed as larval area; e.g. speccode 391. 1455). The combination of the stockcode + larvalarea fields in the table make one row unique. More info on the larvae table here https://www.fishbase.se/manual/English/fishbasethe_larvae_table.htm.
