### ISSUE TITLE
DietTLu vs FoodTroph

### ISSUE THREAD

**Issue by melissaszy** [ropensci/rfishbase#189]
Hello, I am new to rfishbase and have a question. What is the difference between DietTLu and FoodTroph? Alternatively, where can I read about how the various trophic levels types (eg DietTroph, FoodTroph) are calculated? I am trying to find the most suitable trophic level type for my project.

Thank you!
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by Dengaloo** [comment]
Dear all
There are two sources of trophic level estimates in FB and SLB: diet composition based on weight or volume of the food bolus (more reliable source); and the food items known or recorded for a given species that is often accompanied by qualitative categories of preference by the predator and less often of qualitative but incomplete estimation of how much a predator consumes of the prey. When available, the practice is to favour use of TL from diets. However if no diet composition data is available then using the TL from food items is the next choice.
All of these are explained in the Trophic Ecology chapter of the FishBook book a link to which is available in the links below the FishBase logo at the top of the search page.
Thanks
Deng

**Comment by melissaszy** [comment]
Hello Deng,
Thank you for your help. I have another question that I could not find the answer to in FishBook.

what is the difference between the Troph obtained by the following code:
 estimate(vfish_sp$Species, fields=c("SpecCode","Species",
                                                          "Troph","seTroph"))

and the DietTroph and FoodTroph values obtained by the following code:
ecology(vfish_sp$Species, fields = c("SpecCode","Species",
                                                        "DietTroph","DietSeTroph",
                                                        "FoodTroph","FoodSeTroph"))

based on the output, I inferred that the Troph value generated by the estimate command is the DietTroph value, and if that is not available, the FoodTroph value. Is that correct? 

How is the Troph number calculated when both DietTroph and FoodTroph is not available? 

Thank you again.

Cheers,
Mel

**Comment by Dengaloo** [comment]
Hi Mel
Only one of those values are chosen and the default is the DietTroph when both are available.
Thanks
Deng

**Comment by melissaszy** [comment]
Hello Deng,

Thank you for your fast response.

This is the code I used:

library(tidyverse)
library(rfishbase)
library(dplyr)
fish<-c("Acreichthys tomentosus", "Ambassis kopsii", "Amblygobius stethophthalmus", "Anodontostoma chacunda", "Thryssa hamiltonii", "Zenarchopterus buffonis")
Vfish<- validate_names(fish)
vfish_sp<-species(Vfish)
ecology_fish<-ecology(vfish_sp$Species, fields = c("SpecCode","Species","DietTroph","FoodTroph"))
estimate_fish<- estimate(vfish_sp$Species, fields=c("SpecCode","Species","Troph","seTroph"))

From ecology_fish, I noticed that species Amblygobius stethophthalmus (SpecCode 62722) does not have DietTroph and also does not have FoodTroph. Yet in estimate_fish, the same species has a Troph value (ie 2.74).

I'm a bit confused as to where the value is from/ how it is calculated.

Cheers,
Mel

**Comment by Dengaloo** [comment]
This means that the TL was estimated using species in the genus or family and would this have the same or similar feeding behaviour

**Comment by melissaszy** [comment]
Dear Deng,

Thank you once again. What is the difference between DietTLu and DietTroph in the ecology command?

eg
ecology_fish<-ecology(vfish_sp$Species, fields = c("SpecCode","Species","DietTLu","DietTroph","FoodTroph"))

Cheers,
Melissa

**Comment by Dengaloo** [comment]
Not sure. Diet troph is what should be used.

**Comment by melissaszy** [comment]
Dear Deng,

Thank you for your help.

Cheers,
Mel

**Comment by sckott** [comment]
thanks for your question @melissaszy and  @Dengaloo for helping!
