### ISSUE TITLE
Is there a glossary for length type (SPECIES TABLE - LTypeMaxM)?

### ISSUE THREAD

**Issue by anya-mueller** [ropensci/rfishbase#190]
To Whom it May Concern,

I am having trouble figure out what the acronyms for length type mean. for example Crassadoma gigantea LTypeMaxM = SHH.
I have found the definitions for fishbase LTypeMaxM [here](https://www.sealifebase.se/manual/English/fishbasethe_SPECIES_table.htm) but I can't seem to find an equivalent for sealifebase.

I would greatly appreciate any resources or definitions of the LTypeMaxMs for ```server = "seaifebase"```.

Thank you for your time and help.

Cheers,
Anya

**Comment by sckott** [comment]
i don't know but will ask

**Comment by Dengaloo** [comment]
SHH=shell height

**Comment by sckott** [comment]
^ does the above answer your question @anya-mueller ?
