### ISSUE TITLE
rlang issue

### ISSUE THREAD

**Issue by LennWhy** [ropensci/rfishbase#191]
Hello,

I am trying to run some of the script example in R, e.g. validate_names, estimate, etc.., but keep getting the following error message:

Error in switch_lang(call, inlined = , namespaced = , recursive = eval_bare(call,  : 
  could not find function "switch_lang"

I was wondering what I would need to do to fix this issue. Or if you could please direct me to the link where this issues has already been addressed.

Best,
LY

**Comment by sckott** [comment]
if you had shared your session info i could see if you have an old version of `rlang` - you probably need to upgrade that package

**Comment by LennWhy** [comment]
Many thanks for your reply. 
Attached is a screenshot of my session info, along with the rlang error when I type in the script example.
![Screen Shot 2020-11-17 at 17 23 39](https://user-images.githubusercontent.com/56312866/99424876-1b4e8d80-28fa-11eb-92aa-ae7335823176.png)

**Comment by sckott** [comment]
run `traceback()` after that error and paste in the output (not a screenshot)

**Comment by LennWhy** [comment]
> fish <- validate_names(c("Oreochromis niloticus", "Salmo trutta"))
Error in switch_lang(call, inlined = , namespaced = , recursive = eval_bare(call,  : 
  could not find function "switch_lang"
> traceback()
23: lang_partial_eval(call, vars, env)
22: switch_type(call, `NULL` = NULL, symbol = sym_partial_eval(call, 
        vars, env), language = lang_partial_eval(call, vars, env), 
        logical = , integer = , double = , complex = , string = , 
        character = call, formula = {
            f_rhs(call) <- partial_eval(f_rhs(call), vars, f_env(call))
            if (length(call) == 3) {
                f_lhs(call) <- partial_eval(f_lhs(call), vars, f_env(call))
            }
            call
        }, list = {
            if (inherits(call, "lazy_dots")) {
                call <- dplyr:::compat_lazy_dots(call, env)
            }
            map(call, partial_eval, vars = vars, env = env)
        }, abort(glue("Unknown input type: ", class(call))))
21: partial_eval(f_rhs(call), vars, f_env(call))
20: switch_type(call, `NULL` = NULL, symbol = sym_partial_eval(call, 
        vars, env), language = lang_partial_eval(call, vars, env), 
        logical = , integer = , double = , complex = , string = , 
        character = call, formula = {
            f_rhs(call) <- partial_eval(f_rhs(call), vars, f_env(call))
            if (length(call) == 3) {
                f_lhs(call) <- partial_eval(f_lhs(call), vars, f_env(call))
            }
            call
        }, list = {
            if (inherits(call, "lazy_dots")) {
                call <- dplyr:::compat_lazy_dots(call, env)
            }
            map(call, partial_eval, vars = vars, env = env)
        }, abort(glue("Unknown input type: ", class(call))))
19: FUN(X[[i]], ...)
18: lapply(.x, .f, ...)
17: map(call, partial_eval, vars = vars, env = env)
16: switch_type(call, `NULL` = NULL, symbol = sym_partial_eval(call, 
        vars, env), language = lang_partial_eval(call, vars, env), 
        logical = , integer = , double = , complex = , string = , 
        character = call, formula = {
            f_rhs(call) <- partial_eval(f_rhs(call), vars, f_env(call))
            if (length(call) == 3) {
                f_lhs(call) <- partial_eval(f_lhs(call), vars, f_env(call))
            }
            call
        }, list = {
            if (inherits(call, "lazy_dots")) {
                call <- dplyr:::compat_lazy_dots(call, env)
            }
            map(call, partial_eval, vars = vars, env = env)
        }, abort(glue("Unknown input type: ", class(call))))
15: partial_eval(dots, vars = op_vars(.data))
14: mutate.tbl_lazy(., synonym = paste(SynGenus, SynSpecies))
13: mutate(., synonym = paste(SynGenus, SynSpecies))
12: function_list[[i]](value)
11: freduce(value, `_function_list`)
10: `_fseq`(`_lhs`)
9: eval(quote(`_fseq`(`_lhs`)), env, env)
8: eval(quote(`_fseq`(`_lhs`)), env, env)
7: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
6: fb_tbl("synonyms", server, version, db) %>% mutate(synonym = paste(SynGenus, 
       SynSpecies)) %>% select(synonym, Status, SpecCode, SynCode, 
       CoL_ID, TSN, WoRMS_ID, ZooBank_ID, TaxonLevel)
5: synonyms(species_list, server = server, version = version, db = db)
4: eval(lhs, parent, parent)
3: eval(lhs, parent, parent)
2: synonyms(species_list, server = server, version = version, db = db) %>% 
       collect() %>% mutate(Species = ifelse(grepl(rx, Status), 
       Species, NA)) %>% dplyr::group_by(synonym) %>% dplyr::filter(!is.na(Species)) %>% 
       dplyr::ungroup() %>% dplyr::select(synonym, Species) %>% 
       unique %>% right_join(tmp, by = "synonym") %>% pull(Species)
1: validate_names(c("Oreochromis niloticus", "Salmo trutta"))

**Comment by sckott** [comment]
try updating to latest `dbplyr`, restart R, try again

**Comment by LennWhy** [comment]
Brilliant. It works!
Many thanks.
