### ISSUE TITLE
rfishbase as a Dependency for the R package dietr Causing CRAN Check Issues

### ISSUE THREAD

**Issue by sborstein** [ropensci/rfishbase#197]
Hi rfishbase team,

rfishbase is a dependency of my rpackage dietr. I was doing package checks for an update of my package and I am having issues with checks that I have linked back to rfishbase. Specifically, when I do `devtools::check()` on a clean https://github.com/sborstein/dietr clone, we get the following error:

```
my.food <- rfishbase::fooditems(c("Lutjanus apodus","Epinephelus itajara"))
Error: table `tmp_ydgabwknrs` already exists
```

It looks like `tmp_ydgabwknrs` is being created by an `rfishbase:::tmp_tablename()` call. This happens when doing a test on a Mac, Linux, and a Windows machine, with exactly the same random table name, each time. This only seems to be an issue specifically with CRAN checks, otherwise the functions in my R package that depend on rfishbase are behaving properly and pass their unit tests. Please let me know if you need any further information from me and thank you for your work on the rfishbase package.

Thanks,
-Sam Borstein

**Comment by sckott** [comment]
Thanks @sborstein having a look

**Comment by sckott** [comment]
Not sure. @cboettig i'm not sure exactly how tables are being used here, and why this only seems to happen during r cmd check and not when you run examples interactively or on their own

**Comment by sckott** [comment]
@sborstein Seems like cran checks for dietr are clean now, are we all good then, or is this still an issue?

**Comment by sborstein** [comment]
@sckott Yep, all is working now and passing checks. Thanks for looking into this!

**Comment by sborstein** [comment]
Hi rfishbase team,

I am having the exact same issue again that I posted about in March that is preventing my R package dietr from passing CRAN checks. Specifically, when I do `devtools::check()` on a clean https://github.com/sborstein/dietr clone, we get the following error:

```
my.food <- rfishbase::fooditems(c("Lutjanus apodus","Epinephelus itajara"))
Error: table `tmp_ydgabwknrs` already exists
````

Again, it appears `tmp_ydgabwknrs` is being created by an `rfishbase:::tmp_tablename()` call. I have been able to replicate this on both windows and Linux and it is always a table named `tmp_ydgabwknrs`. Like last time, this only appears to be an issue with CRAN checks, otherwise, all aspects of my package (including those that use rfishbase) are working properly and pass tests. 

Please let me know if you can fix this again.

Thanks,
-Sam Borstein

**Comment by cboettig** [comment]
https://github.com/ropensci/rfishbase/blob/5e0038cff0087ae6c0e7ad8bd21b8ed547f35e53/R/00-endpoint.R#L113-L114

right; I guess in most typical use cases the rng won't be in precisely the same state, so `sample` gives different results.  But the testing is strict enough somehow to ensure identical names.  I believe we could do this by choosing a more "true random" technique for table names, e.g. via `openssl::random_bytes()` (which I think is already an implicit dependency).

**Comment by cboettig** [comment]
@sborstein ok, pushed a potential fix in 515376fd0abf4f1e7ff8fe6f1a6bae6bb3696b86, can you try installing the `master` branch from GitHub and see if that resolves the check issue?

**Comment by sborstein** [comment]
Hi @cboettig Thanks for making the change. I installed your push from GitHub and my CRAN checks are now passing locally. Is this something you can push to CRAN soon so I can get my package re-submitted. Thank you for the quick response and bug fix, I appreciate it.

**Comment by cboettig** [comment]
@sborstein patched version should be on CRAN now
