### ISSUE TITLE
Get FAO areas?

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#20]
hoping to look at species distributions per FAO fishing areas and am wondering if it's possible to run a quick query for this within rfishbase for a given list of species? It seems that there isn't a search term for the FAO areas within the function "which_fish" - but the information is on fishbase.org.

**Comment by cboettig** [comment]
Okay, this is implemented in rfishbase2.0 as "locations", e.g. 


```r
faoares(species_list(Genus='Labroides'))
```

gives:

```
  AreaCode SpecCode Status                            FAO
1        2     1520 native America, North - Inland waters
2        4     1520 native           Asia - Inland waters
3       18     1520 native                   Arctic Ocean
4       27     1520 native            Atlantic, Northeast
5       61     1520 native             Pacific, Northwest
6       67     1520 native             Pacific, Northeast
7       77     1520 native       Pacific, Eastern Central
```

This doesn't yet have the "Note" column from the web, not sure if that's needed. ([eg here](http://www.fishbase.us/Country/FaoAreaList.php?ID=1520&GenusName=Clupea&SpeciesName=pallasii+pallasii&fc=43&StockCode=1713&Scientific=Clupea+pallasii+pallasii))

I'm hoping to add the more general functions for the other Distribution-related tables: Countries, Ecosystems, Occurrences, Point map, Introductions, & Faunaf soon.  

rfishbase2.0 still in development, see the [branch](https://github.com/ropensci/rfishbase/tree/rfishbase2.0)

**Comment by wboeger** [comment]
Thanks Carl!  Great!

Walter
