### ISSUE TITLE
validate_names

### ISSUE THREAD

**Issue by melissaszy** [ropensci/rfishbase#200]
Hello,

When I try to use the validate_names function as such:
vfish<-validate_names(unispp)

I get the following error message:
Error: Invalid or closed connection

This function worked fine previously and is only giving me an error message today (after updating rfishbase).
For context, I am using the latest version of rfishbase (version 3.1.6). My r version is the latest one (version 4.0.4). The unispp object i placed into the function is a character vector [1:60].

How should I fix this issue? Thank you!

**Comment by melissaszy** [comment]
update: I uninstalled rfishbase (3.1.6) and reinstalled version 3.0.4 and the validate_names() works now

**Comment by cboettig** [comment]
should be fixed in the most recent version (3.1.7)
