### ISSUE TITLE
load_taxa no longer returns taxa list

### ISSUE THREAD

**Issue by emmywas** [ropensci/rfishbase#207]
Hello, 
load_taxa() no longer returns a data frame or a taxa list at all for me. It loads a list with SQLite connections. I have used load_taxa() many times in the past and it has worked fine. 
I'm using version rfishbase_3.1.7. Is there a change in functionality in the new version/s? 
Thanks again for a great package!

**Comment by cboettig** [comment]
apologies, you can use `dplyr::collect()` to get the data frame back.  (we should fix this in the next release so it happens automatically)

```r
x <- load_taxa()
df <- dplyr::collect(x)
df
```

**Comment by emmywas** [comment]
Thank you for the quick reply @cboettig! 
Will use this until the next release.

**Comment by cboettig** [comment]
fixed now on CRAN
