### ISSUE TITLE
Database release version - plans to update?

### ISSUE THREAD

**Issue by MichaelJSchram** [ropensci/rfishbase#209]
Hello,

I am currently working on a project which incorporates trait data, thus I am working on a number of R queries to collect and aggregate trait (e.g., trophic level, max length) values for ~200 reef fishes. I notice that the most recent available release is 1904, whereas the site is operating on what appears to be 2102(?). Through some admittedly brief searches [(e.g., Issue #163)](https://github.com/ropensci/rfishbase/issues/163) it sounds like a version release for use in the package is rather involved, but at nearly 2 years old the 1904 release seems fairly out of date. 

Just wondering if there are plans for a database release in the near(ish) future?

Thanks!

**Comment by cboettig** [comment]
apologies, some things happened in the past year or so, still working through a backlog.  The Fishbase team recently provided us the most recent database dumps, I will hopefully update the rfishbase cache soon?

**Comment by gfgalbraith** [comment]
Hi there,

Great to hear that the cache is set to be updated soon. I have also been working on pulling traits for reef fishes and have come across numerous species which have length-weight constants on the summary webpage but return NA in a length_weight query. Guessing this will also be the sort of thing the update will resolve?

Cheers!
Gemma

**Comment by jaseeverett** [comment]
Thanks @cboettig . I assume this will also update Sealifebase db's? I'm also getting a lot of different results compared to the website version. An update would be fantastic.

Thanks so much for your work on this software. It's brilliant.

**Comment by cboettig** [comment]
Again sorry for the long delay.  These should be up now.  

There's an unrelated issue of an expired tokens impacting use at the moment, see #216 for a workaround.  There's also a patched version in the CRAN queue (rfishbase 3.1.9) that will resolve it so that setting your own GITHUB_PAT won't be necessary.
