### ISSUE TITLE
common_to_sci in spanish

### ISSUE THREAD

**Issue by ACalleros** [ropensci/rfishbase#210]
Hi, I have this table and I want to get the scientific names from common names in spanish with:
 

> common_to_sci(pesca$especie, Language = 'Spanish')

`<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> especie </th>
   <th style="text-align:left;"> estado </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Abulón </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Almeja </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Anchoveta </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Atún </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bagre </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Baqueta </td>
   <td style="text-align:left;"> Baja California </td>
  </tr>
</tbody>
</table>`

This is the resulting table with names in english. It seems that it is ignoring the language argument. 

`<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Species </th>
   <th style="text-align:left;"> ComName </th>
   <th style="text-align:left;"> Language </th>
   <th style="text-align:right;"> SpecCode </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Engraulis ringens </td>
   <td style="text-align:left;"> Anchoveta </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis mysticetus </td>
   <td style="text-align:left;"> Anchoveta </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 548 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Engraulis ringens </td>
   <td style="text-align:left;"> Anchoveta(=Peruvian anchovy) </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis edentulus </td>
   <td style="text-align:left;"> Atlantic Anchoveta </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 547 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis edentulus </td>
   <td style="text-align:left;"> Atlantic anchoveta </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 547 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis mysticetus </td>
   <td style="text-align:left;"> Pacific anchoveta </td>
   <td style="text-align:left;"> English </td>
   <td style="text-align:right;"> 548 </td>
  </tr>
</tbody>
</table>`

**Comment by cboettig** [comment]
Thanks for the report!  Sorry about that and I'll try and take a look soon

**Comment by ACalleros** [comment]
Thanks, @cboettig! Sorry for the pressure, but I'm stuck with my thesis and this is the only part that's holding me down

**Comment by cboettig** [comment]
Sorry @ACalleros , I'm locked down in other stuff, but meanwhile it's not too hard to bypass the current interface and grab this data (at least with the 2019 version we provide).

When you first import a table, e.g. common_names(), you should see a message referring to the raw table, like this:

```
library(tidyverse)
library(rfishbase)
> common <- common_names()
Importing /home/cboettig/.local/share/R/rfishbase/comnames_fb_1904.tsv.bz2 in 50000 line chunks:
[\] chunk 7	...Done! (in 20.62483 secs)
```

this tells us that the data in that function is coming from the comnames table from April 2019 -- (We're overdue for a new release, sorry!  hopefully later this summer -- we're an all volunteer effort and not directly supported by FishBase).  

You can read that table in directly:

```
common <- readr::read_tsv("/home/cboettig/.local/share/R/rfishbase/comnames_fb_1904.tsv.bz2")
```

and should be good to go.  (The path for you will be different of course, instead of `/home/cboettig/...`.  You can see the root path to all the fishbase tables on your machine with: `tools:R_user_dir("rfishbase")` )

HTH!
