### ISSUE TITLE
Can validate_names return a df

### ISSUE THREAD

**Issue by jaseeverett** [ropensci/rfishbase#212]
It would be great if `validate_names` returned a dataframe, rather than a character vector. At times, perhaps when a species has been split into two species, two "valid" names will be returned. 

For example: 
`validate_names("Acentrogobius multifasciatus")`
[1] "Caffrogobius gilchristi"      "Acentrogobius multifasciatus"

In this example, because we have only asked to validate 1 species, we can deal with it. But if we send a vector of 10 names, and 11 (or more) valid names come back, there is no way to know which validated names align with which original names.

A better solution might be to return a data frame (or have that option as switch) with 3 columns. 1) `Original_Name`, 2) `Valid_Name` and 3) `Changed`, where Changed is TRUE/FALSE.

This is just a thought. I am trying to validate 15K species names, and I need to loop it through one name at a time, because I end up with about 50 more names than I should if I do them all at once.

Thanks for a great package!

**Comment by reedmiller17** [comment]
I've had luck with the following. Say I have a dataframe, with the specieslist as a named column (eg. df$specieslist).

`df$validnames <- validate_names(df$specieslist)`

This way, the column of valid names (or NAs) is parallel to the original list.

**Comment by cboettig** [comment]
I agree, it should return a table.  Meanwhile, consider resolving names against the `synonyms()` table directly instead, like so:

```r
df <- synonyms(my_species)
```
Now, use df$SpecCode to resolve the accepted species name, e.g.

```r
library(dplyr)
valid_species <- species() %>% filter(SpecCode %in% df$SpecCode) 

## accepted names are now in:
vald_species$Species
```
