### ISSUE TITLE
Separating habitat types by saltwater/brackish water/fresh water on the ecology table

### ISSUE THREAD

**Issue by ceri-w** [ropensci/rfishbase#213]
Is there a way to separate habitat types in the ecology table (Neritic/SupraLittoralZone/Saltmarshes/LittoralZone/TidePools/Intertidal/SubLittoral/Caves/Oceanic/Epipelagic/Mesopelagic/Bathypelagic/Abyssopelagic/Hadopelagic/Estuaries/Mangroves/MarshesSwamps/CaveAnchialine/Stream/Lakes/Cave) by saltwater, fresh water and brackish water (e.g which caves would be saltwater caves?)?

**Comment by cboettig** [comment]
@ceri-w Sorry for the slow reply.  Check the `species()` table instead, it has columns for this: `Brack`, `Fresh`, `Saltwater`.  -1 = TRUE, 0 = FALSE.
