### ISSUE TITLE
Error when I want to use 'ecology' function

### ISSUE THREAD

**Issue by daniealmalik354** [ropensci/rfishbase#217]
I got the problem issue when I want to use 'ecology' function from fishbase, could anyone solve it?

thank you, 

> data_edna_eco <- ecology(meta_data_edna_bali_drop_unidentified$Species)
Error in gh_process_response(raw) : 
GitHub API error (401): 
Message: Bad credentials
Read more at https://docs.github.com/rest

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by MichaelJSchram** [comment]
I began getting the same error about 5PM EST yesterday.  I had been using it no problem most of the day after the initial curl error yesterday morning.

**Comment by cboettig** [comment]
Yup, this is the same issue reported in https://github.com/ropensci/rfishbase/issues/216 , see thread for a work-around.  Will issue a patch to CRAN soon so that this credential is no longer necessary.

**Comment by cboettig** [comment]
CRAN version released, updating rfishbase version 3.1.9 should fix this without requiring further credentials etc.
