### ISSUE TITLE
Bad credentials error

### ISSUE THREAD

**Issue by MaximePolicarpo** [ropensci/rfishbase#226]
Hi,

I am facing an issue since few days that I didn't have before. When i try to use the function "validate_names", this error message appear : 

fish <- validate_names(c("Erpetoichthys calabaricus", "Polypterus ansorgii"))

Error in gh_process_response(raw) : 
GitHub API error (401): 
Message: Bad credentials
Read more at https://docs.github.com/rest

Thanks for any help provided,

Maxime

**Comment by cboettig** [comment]
Please update your versions of `rfishbase` and `readr` R packages and try again, thanks.

**Comment by MaximePolicarpo** [comment]
I have updated both packages (I have rfishbase 3.1.7 and readr 2.0.1). This is very weird as rfishbase worked perfectly 2 weeks ago and since then, I did not install or update any packages. 

Thanks a have a good evening, 

Maxime

**Comment by cboettig** [comment]
Yes, the old package started requiring credentials to access data when the original credentials expired.  The latest version sidesteps the need for access credentials to download the fishbase snapshots.

Also note that we recently released the 21.04 snapshot, replacing the 19.04 version of the data.  

thanks for confirming the fix!
