### ISSUE TITLE
Unable to collate nutrients data

### ISSUE THREAD

**Issue by BoardshortsBen** [ropensci/rfishbase#230]
I am trying to pull information on Nutrients, as listed in the web version.

Have tried `list_fields("Nutrients")` with no success in finding the correct function to use.

**Comment by cboettig** [comment]
That's a good question.

We only get periodic dumps from the fishbase database and link them.  Table names in the DB are usually but no always intuitive, I don't spot something that looks like nutrients data in our list: https://github.com/ropensci/rfishbase/releases/tag/fb-21.04.  

As you see, FishBase has lots of tables, and continues to add new ones.  If this table was introduced recently it may not be in the April 2021 (i.e. v21.04) snapshot...

**Comment by BoardshortsBen** [comment]
Ahh, that will be why. Nutrient data was added in June this year for all species so would not be in the April snapshot.

**Comment by tomjwebb** [comment]
Hi @BoardshortsBen - have you tried this again recently? I'm looking today and can access the tables `nutrients` and `nutrientssummary`, but I can't quite figure out how they relate to each other, or to the results that come out of the Nutrient Search tool here https://www.fishbase.in/Nutrients/NutrientSearch.php

I would like to be able to get the results that come out of the nutrient search tool for a list of species, thought I would ask if you have resolved this before I dig any futher…

**Comment by cboettig** [comment]
yeah, unfortunately we only provide direct access to the underlying tables, I don't have further information.  Contacting the FishBase team directly might help?
