### ISSUE TITLE
errrors

### ISSUE THREAD

**Issue by marineLZ** [ropensci/rfishbase#239]
> fish <- validate_names(c("Oreochromis niloticus", "Salmo trutta"))
Error in curl::curl_download(addr, dest = local_tbl) : 
  Timeout was reached: [] Connection timed out after 10001 milliseconds

> devtools::session_info()
- Session info ----------------------------------------------------------------------
 setting  value                         
 version  R version 4.1.1 (2021-08-10)  
 os       Windows 10 x64                
 system   x86_64, mingw32               
 ui       RStudio                       
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 ctype    Chinese (Simplified)_China.936
 tz       Asia/Taipei                   
 date     2021-11-27                    

- Packages --------------------------------------------------------------------------
 package     * version date       lib source        
 arkdb         0.0.14  2021-10-18 [1] CRAN (R 4.1.1)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.1)
 bit           4.0.4   2020-08-04 [1] CRAN (R 4.1.1)
 bit64         4.0.5   2020-08-30 [1] CRAN (R 4.1.1)
 blob          1.2.2   2021-07-23 [1] CRAN (R 4.1.1)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.1)
 cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.1)
 colorspace    2.0-2   2021-06-24 [1] CRAN (R 4.1.1)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.1)
 curl          4.3.2   2021-06-23 [1] CRAN (R 4.1.1)
 DBI           1.1.1   2021-01-15 [1] CRAN (R 4.1.1)
 dbplyr        2.1.1   2021-04-06 [1] CRAN (R 4.1.1)
 desc          1.4.0   2021-09-28 [1] CRAN (R 4.1.1)
 devtools      2.4.2   2021-06-07 [1] CRAN (R 4.1.1)
 dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.1.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.1)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.1)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.1)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.1)
 generics      0.1.0   2020-10-31 [1] CRAN (R 4.1.1)
 ggplot2       3.3.5   2021-06-25 [1] CRAN (R 4.1.1)
 gh            1.3.0   2021-04-30 [1] CRAN (R 4.1.1)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.1)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.1)
 hms           1.1.0   2021-05-17 [1] CRAN (R 4.1.1)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.1)
 jsonlite      1.7.2   2020-12-09 [1] CRAN (R 4.1.1)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.1)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.1)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.1)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.1)
 pillar        1.6.2   2021-07-29 [1] CRAN (R 4.1.1)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.1.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.1)
 pkgload       1.2.2   2021-09-11 [1] CRAN (R 4.1.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.1)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.1)
 progress      1.2.2   2019-05-16 [1] CRAN (R 4.1.1)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.1)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.1)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.1)
 readr         2.0.1   2021-08-10 [1] CRAN (R 4.1.1)
 remotes       2.4.0   2021-06-02 [1] CRAN (R 4.1.1)
 rfishbase   * 3.1.10  2021-11-10 [1] CRAN (R 4.1.2)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.1)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.1)
 RSQLite       2.2.8   2021-08-21 [1] CRAN (R 4.1.1)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.1)
 stringi       1.7.4   2021-08-25 [1] CRAN (R 4.1.1)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.1)
 testthat      3.1.0   2021-10-04 [1] CRAN (R 4.1.1)
 tibble        3.1.4   2021-08-25 [1] CRAN (R 4.1.1)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.1)
 tzdb          0.1.2   2021-07-20 [1] CRAN (R 4.1.1)
 usethis       2.0.1   2021-02-10 [1] CRAN (R 4.1.1)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.1)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.1)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.1)

[1] E:/R/R-4.1.1/library

**Comment by marineLZ** [comment]
> rfishbase::species(version = "19.04")
Error in curl::curl_download(addr, dest = local_tbl) : 
  Timeout was reached: [] Connection timed out after 10000 milliseconds

**Comment by cboettig** [comment]
@marineLZ thanks for the report, that's definitely unexpected.  Could be a temporary connectivity issue though, can you try again and confirm?

If the issue persists, could you also try the current development branch by running:

```
# install.packages("remotes") # first if necessary
remotes::install_github("ropensci/rfishbase@parquet")
```

restart R, and try again?
