### ISSUE TITLE
Discrepancy in vulnerability values and lacking aquarium metadata 

### ISSUE THREAD

**Issue by rikkeonielsen** [ropensci/rfishbase#246]
Hi

1) How can I access the table which includes the data on ‘Climate Vulnerability’? When I download the full data from the estimate table _fb_tbl("estimates")_ in which I expect it to be it is not there. 
When I download the full data _data <- species(fish)_ I get data on 'Vulnerability', but this value does not correspond to the value I expect from the webpage. Does anyone know why this is the case? 
This example is for the species _Sphyrna lewini_ 

![image](https://user-images.githubusercontent.com/71554822/161719238-9319238b-8b39-4487-9598-37ec125bd5d2.png)

![image](https://user-images.githubusercontent.com/71554822/161719260-2ea45b63-3745-4d12-bd04-cdcfa0377f05.png)

2) Additionally, does anyone know how to find the metadata for the aquarium table? Fishbase does not specify what the values mean anywhere in their glossary lists etc. And since I get access to more data using this interface I am as well interested to know exactly what the additional data means. 

![image](https://user-images.githubusercontent.com/71554822/161721059-172b3031-8230-473e-ac66-deebbf276626.png)

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by cboettig** [comment]
rfishbase relies on periodic snapshots (see README) that may lag behind the official web server.  can you test the recent release (Jan 2023 release, aka v23.01)
