### ISSUE TITLE
Where to get the fbapp.sql file?+

### ISSUE THREAD

**Issue by ccaspanello** [ropensci/rfishbase#248]
How are you guys downloading the Fishbase DB dumps?  I was browsing the site and couldn't find them.  Would you mind updating the ReadMe doc with the location?  Thanks

**Comment by cboettig** [comment]
Apologies, FishBase.org provides us the SQL snapshot dumps periodically and we update the file cache. The FishBase team does not distribute the raw SQL dump publicly.  We're probably due for an updated version soon though.

**Comment by ccaspanello** [comment]
Thank you for the response.  Have a good one!
