### ISSUE TITLE
Missing getTropicLevel data?

### ISSUE THREAD

**Issue by xueyingyin** [ropensci/rfishbase#25]
Hi Carl,

I'm using the rfishbase package to gather a series of data for a modelling exercise. I just notice that some of the species that have Tropical Level data on the their fishbase summary pages, when queried using the getTropicalLevel() commend, display only NA. Examples are Carangoides_armatus, Lethrinus_erythracanthus. 

What caused this? Is there a fix?

Many thanks! Xueying

**Comment by jhpoelen** [comment]
@xueyingyin @cboettig just tried:
 
```R
install.packages('rfishbase')
library(rfishbase)
data(fishbase)
getTrophicLevel(fish.data[1:3])
```
and . . . a got the following message:
```
Error in xpathApply(summaryPage, "//*[contains(@href, '/Ecology/FishEcologySummary.php')][1]",  : 
  subscript out of bounds
```

PS Thanks for a all the good work on rfishbase . . . a much needed machine readable method to access fishbase. I wonder why they don't openly publish a dump of their mysql database periodically . . .

**Comment by xueyingyin** [comment]
Hi Jorrit I remember that error message usually shows up when there's no such data (depending on the query code) for the species being queried.

**Comment by fishandfish** [comment]
Hi All,

I just tried to get all the TL data and got the same error as jhpoelen above. Code is 
TLfish<-getTrophicLevel(fish.data=NULL,path=NULL,as_table=FALSE,from=c("diet composition","individual food items"),unfished=FALSE,justSE=FALSE, justReference=FALSE)

Error reads: Error in xpathApply(summaryPage, "//*[contains(@href, '/Ecology/FishEcologySummary.php')][1]",  : 
  subscript out of bounds

Thanks for all you do!
K

**Comment by cboettig** [comment]
Hi All,

this issue will be resolved in rfishbase2.0, along with many other issues that all stem from the web-scraping approach applied in the original rfishbase.  We suspect you will find the new version much more powerful as well. I will follow up here when we have a release candidate available.  Thanks for your patience.

**Comment by fishandfish** [comment]
Thanks so much!
K

**Comment by cboettig** [comment]
Okay, this is now in rfishbase2.0, currently available only through the `ecology` function (so named to match the link you would use from the fishbase summary page; let me know if that's too obscure).

As the function name implies, this table has quite a bit of diverse information (129 fields), it probably makes sense to request just the desired fields.  

```r 
ecology(c("Oreochromis niloticus", "Salmo trutta"),
          fields=c("SpecCode", "FoodTroph", "FoodSeTroph", "DietTroph", "DietSeTroph"))
```

which gives a table like this:

```
  SpecCode FoodTroph FoodSeTroph DietTroph DietSeTroph
1        2      2.02        0.00   2.00000    0.000000
2      238      3.80        0.82   3.15501    0.423867
```

**Comment by jhpoelen** [comment]
@cboettig thanks for all the hard work!
