### ISSUE TITLE
saving/exporting tibble data from searches

### ISSUE THREAD

**Issue by anyelovr** [ropensci/rfishbase#253]
Hello, 

This is a question, not a issue. To be honest, I'm beginner R user that is trying to use a little bit rfishbase to get some diet data on a particular list of species. I've tried to get used to the Rstudio and the package. Finally, I could make them work on my computer and I've managed to get "results" from my searches using rfishbase. However, I'm a little stock on how I can do to save/export the "tibble" data, that I see on my screen (cache) or on the console, to other formats as "cvs" or "xlsx". I tried with "write.csv" from "dplyr" but I dont know what I should put on "x" argument (I'm not sure what the name of these "tibbles") and got stock here. 

Surely this is minor concern, but I would appreciate a lot any kind of help,

Hope you you keep doing well, 
Best wishes
Anyelo

**Comment by cboettig** [comment]
Thanks, learning R can be tough but I think it's worth the investment!  You'll find better support for questions on how to use R in general forums. I highly recommend asking for help on https://community.rstudio.com/, it is a friendly & welcoming community.
