### ISSUE TITLE
estimate() function returns LengthType NA

### ISSUE THREAD

**Issue by LauraMannocci** [ropensci/rfishbase#255]
Hello,

We are using the estimate() function of rfishbase (version 4.0.0) with a vector of our species names as the argument.
```

- Session info -------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows >= 8 x64 (build 9200)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       Europe/Paris
 date     2022-10-21
 rstudio  1.1.463 (desktop)
 pandoc   NA

- Packages -----------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date (UTC) lib source
 cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.1)
 sessioninfo * 1.2.2   2021-12-06 [1] CRAN (R 4.2.1)

 [1] C:/Users/lmannocc/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.1/library


 sp = c( "Abalistes stellatus", "Ablennes hians", "Acanthocybium solandri")
a_b <- rfishbase::estimate(sp)
```

a_b is a table with the following 71 columns,k including Species, a, b etc

However the LengthType column contains only NA. As a result we don’t know if a and b parameters should be applied with length type = FL or length type = TL.

Is it normal that the LengthType column is NA ?

Many thanks

**Comment by LauraMannocci** [comment]
To complement my previous post: when applying the formula weight = a * length^b , how do I know if a and b should be applied to LengthType = FL or  LengthType = TL ?

**Comment by Dengaloo** [comment]
Hi Laura
The length type of the sample should be available in the data record. If it isn’t the. It is assumed as TL.
Thanks
Deng

**Comment by cboettig** [comment]
Thanks Deng
