### ISSUE TITLE
Error in rbind(deparse.level, ...) : 变量的列数不对                                                                            In addition: Warning message: In curl::curl_fetch_memory(url, handle = handle) :   Timeout was reached: [cn.dataone.org] SSL/TLS connection timeout

### ISSUE THREAD

**Issue by ZhisenLuo** [ropensci/rfishbase#258]
library(rfishbase)
species_name = species_list(Family = "Mullidae")

Just test two lines of code, but there is an error:

Error in rbind(deparse.level, ...) : 变量的列数不对                                                                           
In addition: Warning message:
In curl::curl_fetch_memory(url, handle = handle) :
  Timeout was reached: [cn.dataone.org] SSL/TLS connection timeout

![1672931168377](https://user-images.githubusercontent.com/122035734/210811844-3889a281-8893-4732-90c5-dc67a0c306fc.jpg)

**Comment by cboettig** [comment]
thanks for the report!  Can you try again now? (looks like this was just a temporary internet outage)


can you provide the output of:

```r
library(rfishbase)
devtools::session_info()
```

Can you also confirm that you can reach the server mentioned:

```r
httr::HEAD("https://cn.dataone.org")
```

should show Status: 200

**Comment by ZhisenLuo** [comment]
> thanks for the report! Can you try again now? (looks like this was just a temporary internet outage)
> 
> can you provide the output of:
> 
> ```r
> library(rfishbase)
> devtools::session_info()
> ```
> 
> Can you also confirm that you can reach the server mentioned:
> 
> ```r
> httr::HEAD("https://cn.dataone.org")
> ```
> 
> should show Status: 200

Thank you very much. Adding code "devtools::session_info()", it can work! Amazing!
And I wanna ask another question. How could I get the information of IUCN in fishbase using R?

**Comment by Simonestevo** [comment]
Hi there, I think I am having the same issue as the previous user (although it seems like theirs resolved itself). I've tried to use previously working fishbase code on two different machines and receive these errors: 

![image](https://user-images.githubusercontent.com/20852617/212571679-84d31ce0-77d1-4d34-93d1-ae9c5e505538.png)

Outputs from session info and server:

devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Australia.utf8
 ctype    English_Australia.utf8
 tz       Australia/Sydney
 date     2023-01-16
 rstudio  2022.07.2+576 Spotted Wakerobin (desktop)
 pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)

httr::HEAD("https://cn.dataone.org")
Response [https://search.dataone.org/]
  Date: 2023-01-15 22:52
  Status: 200
  Content-Type: text/html
<EMPTY BODY>

I'd be grateful if you could advise! Thanks in advance.

**Comment by cboettig** [comment]
this should be avoided in the current github release (4.1.0), cran release to follow.  please re-open if issue persists
