### ISSUE TITLE
can not install the package

### ISSUE THREAD

**Issue by FishyguyNeel** [ropensci/rfishbase#260]
Error in completeSubclasses(classDef2, class1, obj, where) : 
  trying to get slot "subclasses" from an object of a basic class ("NULL") with no slots
Error: package or namespace load failed for ‘rfishbase’:
 .onLoad failed in loadNamespace() for 'dbplyr', details:
  call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’

**Comment by cboettig** [comment]
thanks but can you please provide a reproducible example?  It's hard to help without knowing what code you are running or on what platform.  see [reprex](https://reprex.tidyverse.org/)
