### ISSUE TITLE
Wrong morphometrics values?

### ISSUE THREAD

**Issue by cpavloud** [ropensci/rfishbase#272]
Hello, 
I am using rfishbase 4.1.2 in R version 4.1.1.
I have a list of species names and I am retrieving their morphometrics using 

`all_fish_Aphia_morphometrics <- morphometrics(species_list = all_fish_Aphia$scientificName)`

However, the values I get are totally different from the ones in the actual fishbase website. 
Do you have any idea why this might be happening?
I have attached some screenshots in case they will help. 

![species_website](https://github.com/ropensci/rfishbase/assets/32954293/4420e401-f102-42d2-9900-65d388af28b5)

![morhphometric_website](https://github.com/ropensci/rfishbase/assets/32954293/00294e84-0da8-4f14-963f-a41d4a0383d8)

![morhphometric_rfishbase](https://github.com/ropensci/rfishbase/assets/32954293/78e003e2-e843-4241-abb1-2f2467393fed)

**Comment by cpavloud** [comment]
Ok, I just found out that the values are provided in pixels and not in cm...
Would it be possible to retrieve the original cm values?


![pixels](https://github.com/ropensci/rfishbase/assets/32954293/8273b997-0346-4ae0-b037-9c7119436045)

**Comment by cboettig** [comment]
these would be good questions to ask the FishBase team.  rfishbase can only access data made available in fishbase.  if fishbase provides some length measurements in pixels, I very much doubt those were converted from 'original cm' values, but guessing that the photograph scale may not have been available, but still useful in determining the relative lengths shown.
