### ISSUE TITLE
Error using getEnviroClimateRange()

### ISSUE THREAD

**Issue by CottonRockwood** [ropensci/rfishbase#28]
Hi Carl-
I'm trying to use getEnviroClimateRange() and it is giving me an error:

    > data(fishbase)
    > test = getEnviroClimateRange(fish.data[3])
    Error in which(value == defs) : 
      argument "code" is missing, with no default
    In addition: Warning message:
    XML content does not seem to be XML: '' 

Oddly, it worked once for me and then has not since.  I'll take a look at the function to see if I can figure out what is going on but would love help if possible.
I'm using R 3.1.0 and loaded rfisheries from GitHub yesterday.  Let me know if you want more info

**Comment by cboettig** [comment]
Closing this as these connectivity issues should largely be fixed in rfishbase2.0
