### ISSUE TITLE
Recommended way to obtain all species that belong to a particular genus

### ISSUE THREAD

**Issue by dbarneche** [ropensci/rfishbase#294]
Hello, I recently installed `rfishbase` v. 5.0.0. I noticed that `species_list` is no longer a function.

What would be the recommended way to obtain all species that belong to a particular genus?

For example, in the past I would run:

```
species_list(Genus = "Labroides")
```

And that would give all the species of Labroides. What's the new way of obtaining that same output?

**Comment by cboettig** [comment]
Great question, apologies for the change.

We now suggest that users use `filter` with the full taxonomy table to isolate any specific group, and use an `inner_join` (aka a "filtering join") to subset specific tables accordingly.  Here is a slightly simplified version of the example now in the README:

```r
library(rfishbase)
library(dplyr)

spawn <- fb_tbl("spawning")
               
# Filter taxa down to the desired species
groupers <- load_taxa() |> filter(Family == "Epinephelidae")

## A "filtering join" (inner join) 
spawn |> inner_join(groupers)
```

**Comment by dbarneche** [comment]
Thanks @cboettig , I appreciate the quick reply.
