### ISSUE TITLE
Request: Common Name

### ISSUE THREAD

**Issue by rBatt** [ropensci/rfishbase#30]
It'd be nice to grab the common name (i.e., "English name"). So for *Gadus macrocephalus*, I could get "Pacific Cod".

**Comment by cboettig** [comment]
@rBatt @emfuller Okay, just added this to the dev version of rfishbase2.0.  

Currently the query takes a string of common names (and optionally the Language they are in) and returns the corresponding scientific name.  Common-name queries do raise the risk of multiple matches, so I'm open to ideas on how to deal with that. Even if we do return an interactive prompt to the user, it would be good to know what data to actually show the user to help them choose -- e.g. would this just be a list of the scientific names that have matched the query?  (This seems particularly frequent in common names in other languages, like the Malay word "Bayan")

p.s. rfishbase2.0 is a ground-up build based directly on the back-end database, so it should be both easier to use and much more powerful then the terrible dinosaur that is the current rfishbase.  If you add any issues now for things you'd like to see, we'll try and get those implemented first.

**Comment by rBatt** [comment]
Awesome, thanks!

I'll check it out soon

**Comment by rBatt** [comment]
Just tried this. Thanks for the work.  Suggestion: possible to narrow output but subsetting returned fields?

So if I do `commonnames("Gadus morhua")`, I get a table with many entries in many languages. Possible to only return English? Also, if many of the English names are the same, possible to only return a unique list?

These are things I can do myself, so are only small quality of life additions. Otherwise, thanks!

**Comment by cboettig** [comment]
Hey Ryan,

You can just add the argument: `Language = "English`"`.

Yeah, the repeated common names in English reflect national differences
(e.g. Aussies vs US common names), But I haven't yet resolved the code
numbers into those regions.  (Actually I think the most recent version
does, but isn't on the test server yet).

  For now, you'd have to just call `unique` on the table column.  For now,
2.0 is aiming to return data frames analgous to each of the tables linked
from the main page, e.g. look like this
http://www.fishbase.org/comnames/CommonNamesList.php?ID=69&GenusName=Gadus&SpeciesName=morhua&StockCode=79
in the case of common names.

2.0 is far from stable yet, and still adding things.  We're also running on
our own test server, which we take up and down as we add things on that end
too.

**Comment by rBatt** [comment]
Yikes, I can't believe I missed that! My apologies.

**Comment by cboettig** [comment]
Okay, i've now added a simpler function to get common names from scientific names. `sci_to_common()` works more-or-less like `common_to_sci()` 

```r
> sci_to_common("Salmo trutta")
[1] "Sea trout"
> 
> sci_to_common("Salmo trutta", Language="English")
[1] "Brown trout"
> 
> sci_to_common("Salmo trutta", Language="French")
[1] "Truite commune"
```

Note that if you give a language it will return the most frequently used name, which isn't necessarily the same as the preferred FishBase name in English (the default when no language is given).  And while "common_to_sci" understands more vague classes like "trout" or "salmon" and will return multiple matches, naturally "sci_to_common" is giving a more specific common name.

Some species don't have common names in FishBase, and the function will return NULL instead.
