### ISSUE TITLE
getGrowth?

### ISSUE THREAD

**Issue by hkindsvater** [ropensci/rfishbase#31]
I would be thrilled to pull out k, Linf, and what type of length measure it is (TL, SL, FL).  But I will say it has been very fun exploring the length, weight,  and age data so far!

**Comment by sckott** [comment]
@cboettig seems like we can easily get this sorted with the new api?

**Comment by cboettig** [comment]
@hkindsvater Thanks for the suggestion! Just be clear, you're going for the kind of numbers that are reported in tables like this: http://www.fishbase.us/PopDyn/PopGrowthList.php?ID=5537&GenusName=Bolbometopon&SpeciesName=muricatum&fc=364

This will be easy in rfishbase2.0, coming very soon.  Please add any other requests you might have too and we should be able to prioritize them for the new version.  Sorry that the current rfishbase sucks so terribly at the moment. We're writing a proper API to the backend of FishBase now which will make things much easier to work with -- I promise you'll like the new version much more.

@sckott Looks like this would be mostly from the PopGrowth http://www.fishbase.org/manual/english/fishbasethe_popgrowth_table.htm

**Comment by hkindsvater** [comment]
@cboettig @sckott Yes those are the numbers I would like; actually I wouldn't mind all of the information in the PopGrowth table. I will think about other requests and no, I don't think the current version sucks! I'll look forward to the next iteration.

**Comment by xueyingyin** [comment]
@cboettig <https://github.com/cboettig> thrilled that there will soon be
rfishbase 2.0! I think the basic input data for EwE modelling (Ecopath with
Ecosim) could be prioritized as a lot of people I know of tried the
rfishbase package because they needed a vast number of data from the
fishbase just for that. Just a thought. :)

**Comment by cboettig** [comment]
@xueyingyin Feel free to open up another issue to point to particular fields from FishBase that you'd like to see.  In general it's easier to know what parameters you're referring to if we can see specific links; 'basic input data' is a bit vague.

**Comment by BrianHayden** [comment]
@cboettig @xueyingyin Hey folks, great developments here! I do social media for the FSBI, if you open up an issue for comments etc I'll push it on our twitter feed and try to get some input from fish biologists

**Comment by sckott** [comment]
@cboettig I added a `/populations` route. to follow good REST practice, changed name from PopGrowth because hard to make that plural without sounding very weird

**Comment by rBatt** [comment]
@cboettig When using taxize to grab common names, I first check for the
common names that have A-Z regex chars (upper and lower). That gets rid of
a lot of non-English names. This might be a bit intense, but how does
Google Translate detect a language? Yikes, though.

On Sat, Feb 7, 2015 at 10:24 AM, Scott Chamberlain <notifications@github.com

**Comment by cboettig** [comment]
@hkindsvater In rfishbase2.0, you can now get the popgrowth table, e.g.


```r
popgrowth("Gadus morhua")
```

or for multiple species: (almost all rfishbase2.0 functions operate on a list of species names; which can be generated by taxonomic group or common names, etc)

```r
cod <- common_to_sci("Cod")
popgrowth(cod, limit=1000)
```

At the moment though I've done nothing to tidy up the returns of this table, so it's not as clean as the web version.  FishBase has about 11 tables related to population dynamics, see the FishBase manual for descriptions: http://www.fishbase.org/manual/english/fishbasepopulation_dynamics00002680.htm If you have any thoughts about which tables to prioritize or how they should be cleaned/tidied, please let us know!
