### ISSUE TITLE
Migrating from earlier versions of rfishbase 

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#33]
Many of the function calls and return types in rfishbase 0.* were relatively crude, and thus it does not make much sense to mimic them. Instead, we should simply provide a guide to users to map any functionality in the original version into the 2.0 version.  

Here's a complete list of functions in the current (v0.2-3) NAMESPACE, along with mappings that exist so far.  Will continue to update this as we get further along in rfishbase2.0.  

- `findSpecies`, `fish_names`, `which_fish(Family/Order/Class = x)`, `getIds`  are all replaced by `species_list()`
- `getDepth()` is now in `species_info()` (see fields list)
- `getEnviroClimateRange()` basic information is in `species_info()`, more details in the various distribution functions and in `ecology()` table.  
- `getFaoArea()` is now `faoareas()`
- `getFoodItems` is now `fooditems()` 
- `getLengthWeight()` is now `length_weight()`
- `getMetabolism` is now `oxygen()`
- `getPictures()` pending ...
- `getPredators()` is now `predators()`
- `getQuantTraits` was a rather arbitrary combination of traits, now better allocated.  Some of these are returned by the general `species_info()` table, others by specific tables such as `morphology()` or `morphometrics()`
- `getRefs()` pending
- `getSize()` is in `species_info()`
- `getTrophicLevel` is in `ecology()`

- `loadCache` and `updateCache` are no longer needed, all functions are live except for queries to the taxa-table, which still uses caching and has `load_taxa(update=TRUE)` to update the cache.

- `which_fish()` There are no longer generic methods to query for which species match certain criteria.  The current approach requires querying the complete table wherein such data are held and filtering that.  Some examples of this should be added to the vignette.

**Comment by fishandfish** [comment]
@cboettig , 
This is great work, keep it up.
Cheers, K

**Comment by cboettig** [comment]
Available tables are given by `heartbeat()`.  Working on API-level documentation that can return a more complete description of what is in each of these tables.
