### ISSUE TITLE
SeaLifeBase?

### ISSUE THREAD

**Issue by rBatt** [ropensci/rfishbase#34]
Any chance of doing something like rfishbase, but for SeaLifeBase.org? They are similar websites.

**Comment by jafflerbach** [comment]
This would be so great!

**Comment by sartonic** [comment]
agreed! is there currently anything like this (API/R package) for invert data?

**Comment by cboettig** [comment]
Hi @rBatt @jafflerbach @sartonic Thanks for the suggestion -- after speaking to the FishBase.org team they were able to get approval for this and have connected us with the backend for SeaLifeBase.  Hopefully we can get a prototype out soon!  

Just waiting on some community reviews of rfishbase meanwhile so we can avoid repeating any mistakes we've made so far.  Will update this thread when we have something.

**Comment by rBatt** [comment]
Wow, that's great! Thanks for keeping us posted.

**Comment by jafflerbach** [comment]
Wonderful! This will be so helpful

**Comment by sartonic** [comment]
Awesome! Looking forward to it

**Comment by cboettig** [comment]
Okay, a pilot version of SeaLifeBase is now available.  For the moment, you should be able to add `server="http://fishbase.ropensci.org/sealifebase"` to most `rfishbase` commands and get queries to SeaLifeBase instead. here's some examples:

```r
common_to_sci("horseshoe crab", server="http://fishbase.ropensci.org/sealifebase")
[1] "Glyptocephalus cynoglossus" "Glossamia wichmanni"       
> creatures <- common_to_sci("horseshoe crab", server="http://fishbase.ropensci.org/sealifebase")
> ecology(creatures, server="http://fishbase.ropensci.org/sealifebase", fields=c("SpecCode", "FeedingType"))

 SpecCode           FeedingType
1       26 browsing on substrate
2    26142                    NA
```

Please give this a test drive and lemme know how it goes!

**Comment by rBatt** [comment]
This is great – I'll definitely test it out!

Quick question before I start testing: It searches either one database or the other, but not both, right?

**Comment by cboettig** [comment]
Right, one or the other depending on if you give the server argument

On Tue, Jun 23, 2015, 5:33 PM Ryan Batt <notifications@github.com> wrote:

> This is great – I'll definitely test it out!
>
> Quick question before I start testing: It searches either one database or
> the other, but not both, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rfishbase/issues/34#issuecomment-114682629>.
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
Closing as this is now implemented.  Will open new issues to address outstanding to-do items such as documentation; for now this will just be left as an alpha level feature for the first CRAN release.

**Comment by afredstonhermann** [comment]
Hi @cboettig -

Working with @jafflerbach and testing out sealifebase we aren't able to get it to work. Using the snippets of code [you provided](https://github.com/ropensci/rfishbase#sealifebase) we get the following error:

```r
> options(FISHBASE_API = "http://fishbase.ropensci.org/sealifebase")
> kingcrab <- common_to_sci("king crab")

Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "NULL"
```

But everything is looking good when using the fishbase API

**Comment by cboettig** [comment]
okay, thanks, thought it might still be wonky.  I'll take a look soon

**Comment by cboettig** [comment]
Looks like the sealifebase taxa table had been lost from cache.  just pushed it back up, so the command should no longer error but still needs some testing.

**Comment by RTreb** [comment]
I did a new install of rfishbase a moment ago and still get the error reported by afredstonhermann:

```R
install.packages("rfishbase", 
                  repos = c("http://packages.ropensci.org", "http://cran.rstudio.com"), 
                  type="source")
library(rfishbase)
options(FISHBASE_API = "http://fishbase.ropensci.org/sealifebase")
kingcrab <- common_to_sci("king crab")
```
returns:

Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "NULL"

Everything appears to be working properly using the fishbase API.

Thanks for taking the time to create and maintain such a useful tool!

**Comment by cboettig** [comment]
sorry, it would help if I remembered to push my changes too.  Try now?

**Comment by afredstonhermann** [comment]
I just uninstalled and reinstalled the rfishbase package and got the same error: 

    > options(FISHBASE_API = "http://fishbase.ropensci.org/sealifebase")
    > kingcrab <- common_to_sci("king crab")
    Error in UseMethod("filter_") : 
      no applicable method for 'filter_' applied to an object of class "NULL"
    > kingcrab
    Error: object 'kingcrab' not found

Sorry to be the bearer of bad news! And second @RTreb - thank you so much for contributing this.

**Comment by cboettig** [comment]
Hmm, @afredstonhermann  did you install from CRAN, from `packages.ropensci.org` or from `install_github()`?  Installing from either of the latter two and then reloading the package should work now.  You can also try `data(sealifebase)`; if the resulting `sealifebase` data.frame isn't there and you just have a NULL, then R hasn't gotten the updated version somehow.  Sorry for the trouble.

**Comment by RTreb** [comment]
I just installed from ```packages.ropensci.org``` and it now works for me. Thanks!

**Comment by afredstonhermann** [comment]
@cboettig I reinstalled it from ```packages.ropensci.org``` and it works perfectly. My bad. Thank you!

**Comment by JoeyBernhardt** [comment]
Hi there,

I'm having trouble accessing the SeaLifeBase data. Following the comments above, I've installed rfishbase as so:

`install.packages("rfishbase", repos = c("http://packages.ropensci.org", "http://cran.rstudio.com"))`

Then, using: 
`options(FISHBASE_API = "http://fishbase.ropensci.org/sealifebase")`
`> kingcrab <- common_to_sci("king crab")`

I get:

`Warning message:
In error_checks(parsed, resp = resp) :
  Unknown MySQL server host 'slbmysql' (0) for query http://fishbase.ropensci.org/sealifebase/comnames?ComName=king%20crab&limit=1000&fields=SpecCode`

When I switch back to using the fishbase API, everything seems to be fine. Is there something SeaLifeBase specific that I'm missing in setting options?

Thanks!

**Comment by sckott** [comment]
@JoeyBernhardt Sorry about that. Getting the same thing. Taking a look

**Comment by JoeyBernhardt** [comment]
Awesome @sckott, thanks so much!

**Comment by sckott** [comment]
@JoeyBernhardt try again, should be working now

**Comment by JoeyBernhardt** [comment]
Hi @sckott, yes it's working for me now. Thanks for being so responsive and helpful.

**Comment by sckott** [comment]
thanks for reporting the problem @JoeyBernhardt
