### ISSUE TITLE
Summary of endpoints / tables to be implemented

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#36]
See https://github.com/ropensci/fishbaseapi/issues/2

Table list, as given under "More Information" on [a species summary page](http://www.fishbase.org/summary/2).  Doesn't quite map to the table list of the SQL, but probably more sensible for the endpoints.  
- [x] Countries
- [x] FAO areas
- [x] Ecosystems
- [x] Occurrences
- [x] Introductions
- [x] Stocks
- [x] Ecology
- [x] Diet
- [x] Food items
- [ ] Food consumption
- [x] Ration
- [x] Common names
- [x] Synonyms
- [x] Metabolism
- [x] Predators
- [ ] Ecotoxicology
- [x] Reproduction
- [x] Maturity
- [x] Spawning
- [x] Fecundity
- [ ] Eggs
- [ ] Egg development
- [ ] Age/Size
- [x] Growth
- [x] Length-weight
- [x] Length-length
- [x] Length-frequencies
- [x] Morphometrics
- [x] Morphology
- [ ] Larvae
- [ ] Larval dynamics
- [ ] Recruitment
- [ ] Abundance
- [x] References
- [ ] Aquaculture
- [ ] Aquaculture profile
- [ ] Strains
- [ ] Genetics
- [ ] Allele frequencies
- [ ] Heritability
- [ ] Diseases
- [ ] Processing
- [ ] Mass conversion
- [ ] Collaborators
- [ ] Pictures
- [ ] Stamps, Coins
- [ ] Sounds
- [ ] Ciguatera
- [x] Speed
- [x] Swim. type
- [ ] Gill area
- [ ] Otoliths
- [ ] Brains
- [ ] Vision

**Comment by sckott** [comment]
@cboettig  removed from the 2.20 milestone, do you want to implement these other tables, or not?
