### ISSUE TITLE
Error: could not find function "validate_names"

### ISSUE THREAD

**Issue by sartonic** [ropensci/rfishbase#37]
I installed rfishbase from github using devtools under R 3.1.2 using OSX Mavericks. When I run validate_names I get the following error:

> Error: could not find function "validate_names"

I am testing it on a single species: validate_names("Abramis brama"). Other functions I have tried like ecology("Abramis brama") are working just fine.

I'm assuming this is similar to the issue here: https://github.com/ropensci/rfishbase/issues/32
since I just tried 

> rfishbase:::validate_names("Abramis brama")

and that seemed to work. Is there a new function that does something similar? 

Thanks!

**Comment by cboettig** [comment]
Thanks for the bug report; that function wasn't fully documented previously
so hadn't been exported to the user NAMESPACE.  I've just pushed an update
that finishes the documentation and exports it, so `validate_names` should
work without the triple colon now.
