### ISSUE TITLE
user agent `rfishbase`

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#39]
@cboettig any interest in including the string `rfishbase` along with the others that httr uses 

```r
curl/7.38.0 Rcurl/1.95.4.5 httr/0.6.1
```

so it would be like 

```r
curl/7.38.0 Rcurl/1.95.4.5 httr/0.6.1 rfishbase/0.1.0
```

allow to differentiate requests from rfishbase vs. those form users not using rfishbase, though I imagine nearly all coming from R will come from this pkg

**Comment by cboettig** [comment]
Sure, haven't set user-agent in httr before, can you send me an example?

**Comment by sckott** [comment]
yeah, I just use a little  helper fxn to get all the user agent info httr passes, then add in the version of the package in which im sending the request, e.g., in this package im playing with:

https://github.com/sckott/httsnap/blob/master/R/get.R#L49-L55
