### ISSUE TITLE
Cannot download from GIT

### ISSUE THREAD

**Issue by benjamindcowburn** [ropensci/rfishbase#42]
Hello! I am trying to down load the most recent version of Rfishbase in order to use the length_weight command. I use this code;
> library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
> devtools::install_github("ropensci/rfishbase")

Which failed (see below)! Why did this happen?

Downloading github repo ropensci/rfishbase@master
Installing rfishbase
Installing dependencies for rfishbase:
dplyr, lazyeval, tidyr

  There is a binary version available (and will be installed) but the source version is later:
      binary source
dplyr    0.2  0.4.1

trying URL 'http://cran.rstudio.com/bin/macosx/contrib/3.0/dplyr_0.2.tgz'
Content type 'application/x-gzip' length 2991757 bytes (2.9 Mb)
opened URL
==================================================
downloaded 2.9 Mb

The downloaded binary packages are in
	/var/folders/3_/f4qx5lb92235mm8_spksxfdw0000gp/T//RtmpJRG46J/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/3_/f4qx5lb92235mm8_spksxfdw0000gp/T/RtmpJRG46J/devtools47d1b77d660/ropensci-rfishbase-503f476'  \
  --library='/Library/Frameworks/R.framework/Versions/3.0/Resources/library' --install-tests 

ERROR: dependencies ‘lazyeval’, ‘tidyr’ are not available for package ‘rfishbase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rfishbase’
Error: Command failed (1)
In addition: Warning message:
packages ‘lazyeval’, ‘tidyr’ are not available (for R version 3.0.2)

**Comment by cboettig** [comment]
Looks like your version of R is several releases out of date; maybe
consider updating?

Or try installing the 'lazyeval' and 'tidyr' dependencies from CRAN, e.g.
with install.packages(), first?

**Comment by btmarti25** [comment]
I had the same problem, and getting a new version of R fixed it.
