### ISSUE TITLE
Reviews - to do

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#45]
reviews requested: 

* @noamross 
* @layamane

**Comment by sckott** [comment]
see #46

**Comment by noamross** [comment]
Is it in-scope to review the API itself here? I don't know the whole story but it seems that the API itself is being developed by ROpenSci to be hosted by rfishbase itself at some point, is that correct?  And that the API is primarily an interface to the FishBase SQL database?

**Comment by cboettig** [comment]
We'd certainly appreciate that if you did -- the API is primarily in Ruby;
code at https://github.com/ropensci/fishbaseapi, but up to you I think.
@sckott thoughts?

**Comment by noamross** [comment]
I won't be able to review the API's code, but I'll give some feedback on
endpoints, etc.

**Comment by sckott** [comment]
@noamross yes, we built the API, but of course any data problems we can't directly fix - we just get the dump from fishbase. If there's anything in the API itself (the endpoints we chose to provide, API behavior, etc.) we can address them

**Comment by sckott** [comment]
@noamross okay, sounds good

**Comment by cboettig** [comment]
Reviews are in (#46 and #49), so we can close this.
