### ISSUE TITLE
Review of rfishbase

### ISSUE THREAD

**Issue by layamane** [ropensci/rfishbase#46]
Fishbase.org serves as a source for user-generated categorical and quantitative data on fish species, providing information on both species-specific summary pages and through linked data tables.
The rfishbase package provides an easy and intuitive way to access and collate these data, which would otherwise require the user to either manually generate their own data tables or navigate to linked pages to individually download them.  rfishbase's species function quickly assembles these data.  The package provides functions that enabled comparisons across multiple species and allowed me to tailor my data tables to variables of interest.  The documentation provides straightforward descriptions of the main functions with examples.  

A major strength of rfishbase is that it does the data wrangling for you - tables are automatically formatted using the plyr and tidyr packages. As a result, I found it easy to visualize my data as a nice ggplot graphic.  

As mentioned in the package documentation, there are hidden data tables that aren't readily apparent from calling the species() command. I found myself wishing I had a function to list the accessible hidden data tables. e.g., I was able to use maturity() and reproduction() to access associated data but got an error trying to access the online recruitment data with recruitment().  Also on my wish list would be a way to list locations for the StockCode values that I found in several of the hidden files.  All in all, thanks for making a really great and useful package!  I'm looking forward to using rfishbase in my research.  

Lauren Yamane

**Comment by sckott** [comment]
Thanks so much @layamane !  

@cboettig Lauren's review is in.  Looks like she has some good feedback on the interface for some functions and some wishlist items. Let her know if you have any further questions.

**Comment by cboettig** [comment]
Looks like these items are now delegated to specific issues, so closing this.
