### ISSUE TITLE
species giving odd subscript error

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/rfishbase#53]
I attempted to walk through the instructions in the readme and got the following error:

```
> species(fish[1:2])
Error in `[[.default`(col, i, exact = exact) : subscript out of bounds
````

**Comment by cboettig** [comment]
Thanks for the bug report, not sure why this hasn't shown up in our automated tests.

Looks like the recent update to the database changed the classes on some fields. should be fixed in the version just pushed to github.
