### ISSUE TITLE
locations for the StockCode values

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#57]
Should be a straight forward task with the `stock` table

**Comment by sckott** [comment]
what exactly do you want done? a new route or add some data from one table to another?

**Comment by cboettig** [comment]
I believe addressing #80 should fix this.

**Comment by sckott** [comment]
okoay

**Comment by sckott** [comment]
is this sorted out?, given #80 is closed

**Comment by cboettig** [comment]
yups
