### ISSUE TITLE
length_length() reports curl error with url$query is NULL

### ISSUE THREAD

**Issue by mlandis** [ropensci/rfishbase#58]
First I'd like to say rfishbase v2 is a wonderful resource. Thanks for making it available during development.

A few weeks ago I was able to call length_length() to query length records following the syntax provided [here](https://github.com/ropensci/rfishbase/blob/master/R/population_dynamics.R). When I called the function this morning, I received the following error:

```
> length_length("Oreochromis niloticus")
Error in curl::curl_escape(url$query) : `url` must be a character vector.

Enter a frame number, or 0 to exit   

1: length_length("Oreochromis niloticus")
2: dplyr::bind_rows(lapply(codes, function(code) {
    if (!is.null(fields)) 
        fields <- c(
3: lapply(codes, function(code) {
    if (!is.null(fields)) 
        fields <- c("SpecCode", field
4: FUN(2[[1]], ...)
5: httr::GET(paste0(server, "/", endpt), query = args, ..., httr::user_agent(make_ua()))
6: handle_url(handle, url, ...)
7: build_url(modifyList(old, new))
8: curl::curl_escape(url$query)

Selection: 8
Called from: top level 
Browse[1]> url$query
NULL
```
Any thoughts? Best, Michael

**Comment by cboettig** [comment]
Michael, thanks for the kind words.  Advice on how to make it better (either docs or interface) always welcome.  

Very strange, I cannot seem to reproduce this error; it still works for me.   Can you try reinstalling from github first?  Also, can you give me the output of `sessionInfo()`?

**Comment by sckott** [comment]
@mlandis I think that is related to `httr`

@cboettig  I think we should force `httr >= v1`  in  https://github.com/ropensci/rfishbase/blob/master/DESCRIPTION#L18  - which has various fixes, importantly avoiding the dreaded multi handle error, but does mean that you can't pass empty lists to the `query` parameter, which I think causes that error

**Comment by mlandis** [comment]
@cboettig @sckott Nice catch! :fishing_pole_and_fish: Upgrading to `httr_1.0.0` fixed this (possibly in conjunction with reinstalling rfishbase from github). Interestingly, I do not receive any error from my Berkeley workstation, which has `httr_0.6.1` installed. Thanks for the help.

**Comment by cboettig** [comment]
@sckott nice catch! @mlandis my bad; `httr (>= 1.0.0)` is now enforced in the DESCRIPTION, which should help avoid this.  

(btw, I think `install_github()` now forces everything to upgrade to the latest CRAN version anyway -- that is, if you're running the most recent devtools at least)...
