### ISSUE TITLE
Document SeaLifeBase

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#62]
Basic access implemented in #34, but essentially an invisible method in 2.1.0.  Needs proper documentation, testing, and further development to be a first-rate citizen in rfishbase.  Perhaps development should fork to a new package to enable better discovery of a SeaLifeBase R interface.

**Comment by sckott** [comment]
Hmmm, but the infrastructure is very shared though, so maybe makes sense to keep both in the same pkg 

could use better docs though I suppose

keep in this milestone or move to `2.3.0`?

**Comment by cboettig** [comment]
agree that we should keep them linked given the overlap.  Re documentation, true but of course a bit vague.  I think the key thing would be to put somewhere clearly in the package DESCRIPTION and Vignette that the package is an interface to both FishBase and SeaLifeBase?

**Comment by sckott** [comment]
> put somewhere clearly in the package DESCRIPTION and Vignette that the package is an interface to both FishBase and SeaLifeBase

yeah, makes sense, can do
