### ISSUE TITLE
Add "estimates" endpoint

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#63]
As suggested in thread in #35

**Comment by sckott** [comment]
@cboettig added an `/estimate` route - let me know at your convenience if it looks good

**Comment by cboettig** [comment]
LGTM.  Think we need an entry for the endpoint in `/docs`, e.g. update https://github.com/ropensci/fishbaseapi/blob/master/docs/docs-sources/tables.csv

**Comment by sckott** [comment]
okay, will do

**Comment by sckott** [comment]
what do you think is a good entry for `/estimate` in the table?

**Comment by sckott** [comment]
added, though can't find any description of the `estimate` table in the manual, so not sure what to put in there
