### ISSUE TITLE
sealifebase/taxa "server error"

### ISSUE THREAD

**Issue by luigi-asprino** [ropensci/rfishbase#68]
Hi,
Thank you for your work. It is very helpful.

It seems that the taxa API does not work.
I tried: http://fishbase.ropensci.org/sealifebase/taxa? 
and I got this response: {"error":"server error"}

**Comment by sckott** [comment]
hi @luigi-asprino I'll take a look and get back to you soon....

**Comment by sckott** [comment]
almost there...

**Comment by sckott** [comment]
This should work soon - deploying the fix to the server shortly:
 
http://fishbase.ropensci.org/sealifebase/taxa?species=carina&limit=3

**Comment by luigi-asprino** [comment]
Great!!
Thank you so much!!

**Comment by sckott** [comment]
np, so that works for you?

**Comment by sckott** [comment]
np, so that works for you? @luigi-asprino

**Comment by luigi-asprino** [comment]
yes, it works

**Comment by sckott** [comment]
great!

**Comment by luigi-asprino** [comment]
Hi @sckott,  
Sorry, yesterday I did not notice that the parameter "offset" is ignored.
The requests http://fishbase.ropensci.org/sealifebase/taxa?limit=1&offset=0 and  http://fishbase.ropensci.org/sealifebase/taxa?limit=1&offset=1 return the same result.

**Comment by sckott** [comment]
@luigi-asprino sorry about that! I'll have a look and hopefully get it fixe right away

**Comment by sckott** [comment]
fixed in https://github.com/ropensci/fishbaseapi/commit/6c5560999d57c04f1cd32d9b3da24e0f34334afe

those example should work now @luigi-asprino

**Comment by luigi-asprino** [comment]
Hi @sckott,
thank you, but it seems the same problem exists for the API taxa.
http://fishbase.ropensci.org/taxa?limit=1&offset=1
http://fishbase.ropensci.org/taxa?limit=1&offset=0

**Comment by sckott** [comment]
@luigi-asprino Sorry about that!  Fixing now, For some reason, I decided not to allow the `offset` parameter in the `/taxa` routes, no goo reason for that though

**Comment by sckott** [comment]
@luigi-asprino okay, should work now

As we build out the test suite for these APIs, hopefully you'll run into less problems :)

**Comment by luigi-asprino** [comment]
@sckott thank you for your quick fix. 
Don't worry about the bugs :) I know you are in testing phase.

**Comment by sckott** [comment]
no problem, thanks for reporting the problem
