### ISSUE TITLE
Data set ‘all_taxa’ not found

### ISSUE THREAD

**Issue by iwanicki** [ropensci/rfishbase#69]
Hi all,

This might be a silly question as I am new to R. I've been trying to run rfishbase package to identify Family names for a set of species, but always get the same error:

data(all_taxa)
all.fish = all_taxa[,c(2,3,10)]
sname = as.character(unlist(str_join(all.fish$Genus, all.fish$Species, sep = " ")))
all.fish = data.frame(sname, all.fish$Family)
names(all.fish) = c("sname", "Family")

Warning message:
In data(all_taxa) : data set ‘all_taxa’ not found

Any insights? 
Thanks!

**Comment by cboettig** [comment]
@iwanicki I think you are looking for the function `load_taxa()` to get the taxa table.  e.g. 

```r
all.fish <- load_taxa()
all.fish[,c("Genus", "Species", "Family")]
```

btw, if you'd prefer joining the species and genus names, you might prefer:

```r
all.fish$Species <- paste(all.fish$Genus, all.fish$Species)
all.fish[,c("Species", "Family")]
```

Feel free to close the thread if this resolves your issue.

**Comment by cboettig** [comment]
@iwanicki closing this because I think the above should address it; please re-open if the issue persists.
