### ISSUE TITLE
SeaLifeBase API not working

### ISSUE THREAD

**Issue by LoTreb** [ropensci/rfishbase#70]
Hi there,
in attempting to query sealifebase, I was unable to connect using the given API example.  

options(FISHBASE_API = "http://fishbase.ropensci.org/sealifebase")
kingcrab <- common_to_sci("king crab")
kingcrab

Please advise or send a status update.  Thank you

**Comment by cboettig** [comment]
Yes, apologies. Looks like the cached taxa table for sealifebase data was lost.  Please try installing from github and give it another go.  Sealifebase was only recently added and hasn't been tested thoroughly, so do ping me if things break or you start getting unexpected results.

**Comment by LoTreb** [comment]
Thanks Carl.  Managed to get it partly working, however, I am unable to extract common names using my list of scientific names.  It worked for fishbase and now I have a few hundred invertebrates to collect common names for.  Thoughts?

**Comment by LoTreb** [comment]
Seems to be working now.  Thanks!
