### ISSUE TITLE
rFishBase  request timed out

### ISSUE THREAD

**Issue by amroco** [ropensci/rfishbase#71]
I am using rFishBase to query information from the FishBase website.
Although the package was working fine for me last week I have been getting the following error:

> synonyms("valid_name")

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
In addition: Warning messages:
1: In parse_name(species) : NAs introduced by coercion
2: In parse_name(species) : Species  valid_name could not be parsed
> 

I have not been able to find a solution to this error online and would appreciate your help :)
Thanks,
A

**Comment by sckott** [comment]
@amroco Sorry about that, Looks like our server is having trouble, looking at it

**Comment by aammd** [comment]
Myself and @joeybernhardt are having the same issue, FYI :fish:

**Comment by sckott** [comment]
thanks for reporting @aammd - trying to sort out problem

**Comment by cboettig** [comment]
Looks like XSEDE Chameleon servers are down right now. downside of using NSF resources :/  should be back up some time today...

**Comment by sckott** [comment]
thanks @cboettig

**Comment by amroco** [comment]
legends, thanx @sckott  @cboettig

**Comment by JoeyBernhardt** [comment]
Yes, I'm running into the same issues, getting the 'couldn't connect to server' error.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server

Thanks for looking into this!

**Comment by cboettig** [comment]
Hi everyone, sorry for the server going down and the slow time in bringing it back up.  We'll look into what we can do to speed that up in the future.   Anyway, it should be back up now.  Ping us here if you encounter any further issues.

**Comment by JoeyBernhardt** [comment]
great, thanks a lot!

**Comment by eric-pedersen** [comment]
Not sure if this is the right place for this, but it looks like the Rfishbase server has gone down again; I'm getting the error message "Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received"

I'm also not able to open fishbase.ropensci.org

**Comment by sckott** [comment]
we're working on it, as always, our server provider is down again. will get it back up as soon as we can get back in to the server

**Comment by sckott** [comment]
@eric-pedersen back up

**Comment by cboettig** [comment]
@eric-pedersen Thanks!  I'd also encourage you to try our new candidate development version for rfishbase 3.0:

run 

```r
devtools::install_github("ropensci/rfishbase@3.0")
```

and restart R.  The new version should be considerably faster (particularly for very large queries, and particularly after it 'warms up' on the first call)
