### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by Minato77** [ropensci/rfishbase#72]
I began to use the new version of rfishbase using API in the last weekend.
It worked and helped my research for a few hours, but after that an error like below has been showing up.

> heartbeat()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

What happened?
Is it an internal problem of my network, or has anything happened to the server?

I apologize for my lack of knowledge on API.

Kind regards,

Minato

**Comment by cboettig** [comment]
Sorry, yes, the server is down at the moment, working to get it back up.  (We've been experimenting a bit with different providers, the NSF XSEDE services have been pretty unstable recently so we're switching now to Amazon)

**Comment by Minato77** [comment]
Thank you very much.
I hope it works better.

**Comment by cboettig** [comment]
Okay, should all be back up now.
