### ISSUE TITLE
Error with query

### ISSUE THREAD

**Issue by amroco** [ropensci/rfishbase#75]
Hi there, getting the following error:
Any thoughts?

> valid_name <- validate_names(c("Opistognathus maxillosus"))
Warning messages:
1: In error_checks(parsed, resp = resp) :
  Mysql2::Error: Unknown column 'ColStatus' in 'field list': SELECT  SynGenus,SynSpecies,Valid,Misspelling,ColStatus,Synonymy,Combination,SpecCode,SynCode,CoL_ID,TSN,WoRMS_ID FROM `synonyms` WHERE `synonyms`.`SynSpecies` = 'maxillosus' AND `synonyms`.`SynGenus` = 'Opistognathus' LIMIT 50 for query http://fishbase.ropensci.org/synonyms?SynSpecies=maxillosus&SynGenus=Opistognathus&limit=50&fields=SynGenus%2CSynSpecies%2CValid%2CMisspelling%2CColStatus%2CSynonymy%2CCombination%2CSpecCode%2CSynCode%2CCoL_ID%2CTSN%2CWoRMS_ID
2: No match found for species 'Opistognathus maxillosus' 
> 

Cheers,
A

**Comment by cboettig** [comment]
Hmm, I cannot replicate this error.  Can you give me the output of `sessionInfo()`?

@sckott Can you replicate?  I'm not sure exactly where that API query is coming from, the query in the URL link above does indeed give that error. However, the validate_names() function on the species listed seems to work fine for me in `rfishbase` `v2.1.0`:

```r
valid_name <- validate_names(c("Opistognathus maxillosus"))
> valid_name
[1] "Opistognathus maxillosus"
```

**Comment by sckott** [comment]
That works for me.

**Comment by sckott** [comment]
closing as works for us, and inactivity
