### ISSUE TITLE
Allow "endpoint()" based functions to query on arbitrary field without giving species

### ISSUE THREAD

**Issue by cboettig** [ropensci/rfishbase#80]
e.g. something like `country(query = list(C_Code=440))` should be possible.

**Comment by sckott** [comment]
what do you mean?

**Comment by cboettig** [comment]
currently all functions created via `endpoint()` closure are designed to take a list of scientific names as the argument.  These get converted to a SpecCode and the results are returned.  Some users have requested being able to do a search where instead of giving a list of species names, they'd like to give some other key, like country name (or country code).  The API allows this I think, since we cover arbitrary queries, but there's no easy way to do it in the `rfishbase` functions right now.

**Comment by sckott** [comment]
Right, well almost all routes allow arbitrary queries on their fields, so I guess it's just a matter of implementing here. I think your example above `country(query = list(C_Code=440))` looks reasonable to me, where `query` gets passed into query in the `GET` call (combined with other query params as needed

**Comment by boopsboops** [comment]
A big +1 for this functionality from me! A couple of times I've tried to make a regional species list of fishes, but with no success in rfishbase.

Even with the list of all species names, I still could not figure out how to access the country table and then subset. Any tips on a workaround would be appreciated!

**Comment by sckott** [comment]
hey @boopsboops we'll try to get this implemented soon

**Comment by boopsboops** [comment]
Awesome, thanks!

**Comment by sckott** [comment]
sorted
