### ISSUE TITLE
diet percent

### ISSUE THREAD

**Issue by dchag** [ropensci/rfishbase#87]
Is it possible to query the diet percent information from Fishbase?  That is, the Food and Feeding Habits Summary table for each diet reference accessed by clicking on the main food item in the diet table on Fishbase.

**Comment by sckott** [comment]
thanks for your question @dchag - can you give an example query?

**Comment by dchag** [comment]
In Fishbase, one can click on the main prey item in the diet table (one row for each diet reference) and it takes you to another table with the percent diet for all prey items in that study (below).  Basically, I want to drill down another layer into the rfishbase:diet function.  Each row that is output by the diet function has the percent diet information behind it on Fishbase.


Diet percent

Food I

Food II

Food III

Prey stage

Comments

94.00 %

zooplankton

plank. crust.

plank. copepods

juv./adults

Calanoida

2.40 %

zooplankton

plank. crust.

plank. copepods

recruits/juv.

1.6% Calanoid copepodite, 0.8% other copepodite species

3.10 %

zoobenthos

benth. crust.

benth. copepods

juv./adults

Harpacticoida

0.50 %

zoobenthos

benth. crust.

benth. copepods

recruits/juv.

Harpacticoid copepodite

**Comment by sckott** [comment]
Okay, I haven't changed anything on the fishbase API yet, but if we pull in data from the `diet_items` table to the `/diet` route, then search using `diet("Oreochromis niloticus")` we get the additional columns in the resulting data.frame

```r
$ FoodI          : chr  "plants" "plants" "plants" "plants" ...
 $ FoodII         : chr  "phytoplankton" "phytoplankton" "phytoplankton" "phytoplankton" ...
 $ FoodIII        : chr  "blue-green algae" "blue-green algae" "blue-green algae" "blue-green algae" ...
 $ Stage          : chr  "n.a./others" "n.a./others" "n.a./others" "n.a./others" ...
 $ DietPercent    : num  1 3.3 5.4 27.2 53.4 ...
 $ ItemName       : chr  "Arthrospira" "Merismopedia" "Microcystis" "Chroococcus" ...
 $ Comment        : chr  "<i>Arthrospira</i>" "<i>Merismopedia</i>" "<i>Microcystis</i>" "<i>Chroococcus</i>" ...
 $ DietSpeccode   : logi  NA NA NA NA NA NA ...
 $ DietSpeccodeSLB: logi  NA NA NA NA NA NA ...
 $ AlphaCode      : logi  NA NA NA NA NA NA ...
 $ PreyTroph      : logi  NA NA NA NA NA NA ...
 $ PreySeTroph    : logi  NA NA NA NA NA NA ...
 $ PreyRemark     : logi  NA NA NA NA NA NA ...
```

In addition, the data.frame in this case is 39 rows instead 7 rows, which you get with the current API.  This is because for each row of data in the diet table there are potentially multiple rows in the diet_items table. The fishbase.org website collapses those rows in diet_items on their site, e.g., http://www.fishbase.org/TrophicEco/DietCompoList.php?ID=2&GenusName=Oreochromis&SpeciesName=niloticus&fc=349&StockCode=1 - whereas we can't do that so much

thoughts @cboettig @dchag

**Comment by dchag** [comment]
I think the diet function is misleading, because it returns the collapsed diet_items per fishbase.  Fishbase simply collapses each diet reference to provide only the dominant prey item, omitting the rest of the prey items.  Perhaps change it to return the diet_items table like you did below… or create a new function all together.  This would be incredibly useful for building trophic-dynamic ecosystem models.  Thank you for looking into it and thank you for developing this package.

Dave

**Comment by sckott** [comment]
@dchag not clear to me, so do you prefer to only get back the dominant item from the `diet()` function like the Fishbase site shows?  Or do you want the detailed data back (expanded with all items, not just dominant)?

**Comment by dchag** [comment]
I prefer the detailed diet information, all items, with percentages.  Sorry for the confusion.

**Comment by sckott** [comment]
thanks @dchag

**Comment by sckott** [comment]
@dchag okay, try again requesting data from the `diet()` function, added the extra fields to the diet route from the `diet_items` table

**Comment by sckott** [comment]
a fix needed for sealifebase https://github.com/ropensci/fishbaseapi/issues/90 working on now

**Comment by sckott** [comment]
above is sorted now, `sealifebase/diet` works now

**Comment by dchag** [comment]
At first glance, this appears to working great now.  Thank you.

**Comment by sckott** [comment]
great! glad to hear it
