### ISSUE TITLE
OrdCode and ClaCode access

### ISSUE THREAD

**Issue by amroco** [ropensci/rfishbase#88]
Looking at whats available using the species function I can see GenCode, SpecCode and FamCode,
but nothing for higher levels such as order and class.

Is there a way to access these?
Thank you :)

**Comment by cboettig** [comment]
The `species_list()` function will allow you to search by Order etc by creating a list of species in the requested taxon level.  The FishBase database doesn't define or use codes corresponding to Order or Class, but you should be able to make any query you need by just filtering on the corresponding species names as provided by `species_list()`.  HTH,

**Comment by amroco** [comment]
Hi Carl,
I no longer need this as I got a hold of the list, but in case anyone else would like to operate at higher level taxon, there are codes for higher levels used in fishbase and sealifebase, 
just thought I'd put it out there in case that's something other people may need sometime.
Cheers

**Comment by sckott** [comment]
thanks @amroco - what are some examples of higher level codes?

**Comment by amroco** [comment]
Here is an example from SeaLifeBase:

Phylum: Arthropoda (0),
Class: Maxillopoda (10046)
Order: Harpacticoida (10046)
Family: Novocriniidae (4540)
Genus: Novocrinia (25029)

Cheers,
A

**Comment by sckott** [comment]
thanks

**Comment by amroco** [comment]
Oop, the class and order codes are unique, I accidentally copied and pasted the same value there. Anyway, there are values for those : )
