### ISSUE TITLE
retrieval of trophic level

### ISSUE THREAD

**Issue by marchtaylor** [ropensci/rfishbase#91]
I noticed that a previous version of rfishbase (0.2-2) allowed for the retrieval of trophic level: http://www.inside-r.org/packages/cran/rfishbase/docs/getTrophicLevel

The "getTrophicLevel" doesn't exist anymore, but is this still possible with another approach? species() doesn't seem to return this field.

Cheers,
Marc

**Comment by cboettig** [comment]
I believe it is in the `ecology()` table. Also see `listfields()` to discover a in which tables a keyword appears

**Comment by marchtaylor** [comment]
Great! That did it:

list_fields("Troph")
eco <- ecology("Triaenodon obesus")
eco["DietTroph"]
eco["DietSeTroph"]
