### ISSUE TITLE
Fxn to get taxonomy

### ISSUE THREAD

**Issue by sckott** [ropensci/rfishbase#92]
via `/taxa` route, wrapped already but its an internal fxn. okay if we have an exported fxn for users to get taxonomy data from the `/taxa` route @cboettig ?

**Comment by sckott** [comment]
@cboettig does this make sense to have a function for? or not? does something in this pkg already do this?

**Comment by cboettig** [comment]
Sure, no harm in exporting if it is useful

**Comment by sckott** [comment]
okay, for next milestone

**Comment by sckott** [comment]
closing, if someone wants this we can do it later
