### ISSUE TITLE
Update cache error

### ISSUE THREAD

**Issue by amroco** [ropensci/rfishbase#98]
Apologies if this is something you are currently working on, or have fixed.
However trying to update the cache and run some functions gets me this:

> load_taxa(update=TRUE)
> Error in load_taxa(update = TRUE) : object 'SEALIFEBASE_API' not found
> all.fish <- load_taxa()
> Error in load_taxa() : object 'SEALIFEBASE_API' not found

Thanks,
A

**Comment by sckott** [comment]
do you have most recent from github? what version of the pkg do you have?

**Comment by sckott** [comment]
that's just a constant set in the pkg here https://github.com/ropensci/rfishbase/blob/master/R/load_taxa.R#L7 so not sure why that error is happening

**Comment by amroco** [comment]
Hm, well I reinstalled the package from the link you gave me this morning in relation to the lat and long issue using:
devtools::install_github("ropensci/rfishbase", force = TRUE)
before that I had installed from here:
devtools::install_github("ropensci/rfishbase@sckott-endpoint-fix")


Just tried load_taxa again and now get this error:

Warning in load_taxa(update = TRUE) :
  Did not recognize API, assuming it is fishbase
Error in load_taxa(update = TRUE) : could not find function "GET"

Is there another way to load the latest version of the cache?
This problem wasn't occurring until I reinstalled the package this morning.
Thanks, : )

**Comment by sckott** [comment]
> could not find function "GET"

hmm, that shouldn't happen. Did you restart your session after reinstalling?

**Comment by amroco** [comment]
Ok, problem fixed!
: )
As always, best solution is to turn it off and on again..

**Comment by sckott** [comment]
great, glad it works now!

**Comment by amroco** [comment]
Ok! So, I have updated the cache, using:
load_taxa(update=TRUE)

Then queried for depth, however there are a large number of species which have depth information on FishBase (e.g. Ammodytes marinus), which return NAs for depth when I query them using rFishBase.
As the query returns results for some species but not all I think this must be a cache issue?

Best,
A

**Comment by sckott** [comment]
there was a fix to that fxn that may fix your problem (not sure though) about 18 hrs ago https://github.com/ropensci/rfishbase/commit/cb51387664bf715e94c734ae7787f8e9604e674e - if you don't have latest can you reinstall and try again?

**Comment by amroco** [comment]
No luck so far:

Reinstalled rFishbase:
devtools::install_github("ropensci/rfishbase", force = TRUE)

Updated cache:
load_taxa(update=TRUE)

Queried test species:
example = validate_names("Ammodytes marinus")
example
res <- list()
for (i in seq_along(example)) {
  cat(i, sep = "\n")
  res[[i]] <- species(example[i], fields= c("DepthRangeShallow",
                                              "DepthRangeDeep"))
}
species_depth = dplyr::bind_rows(res)
species_depth

Still getting NAs where there should be values.
Thanks,
A

**Comment by amroco** [comment]
Getting this warning:
> load_taxa(update=TRUE)
Warning in error_checks(parsed, resp = resp) :
  Returning first 5000 matches parsed of 33104 matches. 
 Increase limit or refine query

**Comment by sckott** [comment]
those values are NULL/NA in the API as well

**Comment by sckott** [comment]
@amroco can you show me where on the fishbase website, or a screenshot at least, where you see the values

**Comment by sckott** [comment]
also, `load_taxa` has a `limit` parameter - you need to set that to higher to get all data cached,

* fishbase, use `35000L`
* sealifebase, use `120000L`

the default size it gets is 5000 for each

**Comment by amroco** [comment]
Ok,
added limit, so load taxa looks like:
load_taxa(update=TRUE, limit = 35000L)

The species "Atherion africanum" when queried gives
DepthRangeShallow NA
DepthRangeDeep 2

But on FB, has a depth range of 0-10
![scrnsht](https://cloud.githubusercontent.com/assets/15618227/14125981/f437e10c-f5c2-11e5-9366-1e829193edbb.jpg)

I think what was happening with "Ammodytes marinus", was instead of a depth range, the species has a "usual depth range", however this is not the case with "Atherion africanum".

I think I am probably not updating the cache properly.

**Comment by sckott** [comment]
weird, still can't sort out where that depth information comes from - even searching all fields in all tables only results in 


```r
list_fields("Depth")
#> Source: local data frame [8 x 2]
#> 
#>   table_name          column_name
#>        (chr)                (chr)
#> 1      poplf             DepthMin
#> 2      poplf             DepthMax
#> 3    species    DepthRangeShallow
#> 4    species       DepthRangeDeep
#> 5    species        DepthRangeRef
#> 6    species DepthRangeComShallow
#> 7    species    DepthRangeComDeep
#> 8    species          DepthComRef
```

and checking those results in the same you show above. 

There must be some other data source that Fishbase folks are pulling from. I'll see If I can find out

**Comment by sckott** [comment]
@cboettig any insight on this issue? See screenshot two comments above where depth is in middle of a string of text under an `Ecology` section - but that `depth rang 0-10` is not reflected in the data in the SQL DB/API - AFAICT - any thoughts on whether they might be getting this data from somewhere else, or if I'm just missing it

**Comment by cboettig** [comment]
Not clear to me either.  The species summary page does do a weird mix of
things though relative to the database -- guess we should ask Ranier Froese
about this one.

On Tue, Mar 29, 2016, 5:26 PM Scott Chamberlain <notifications@github.com>
wrote:

> @cboettig <https://github.com/cboettig> any insight on this issue? See
> screenshot two comments above where depth is in middle of a string of text
> under an Ecology section - but that depth rang 0-10 is not reflected in
> the data in the SQL DB/API - AFAICT - any thoughts on whether they might be
> getting this data from somewhere else, or if I'm just missing it
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rfishbase/issues/98#issuecomment-203168197>
>
-- 

http://carlboettiger.info

**Comment by sckott** [comment]
We're looking into this with the Fishbase folks...

**Comment by amroco** [comment]
Awesome, thanks for this guys!

**Comment by sckott** [comment]
@amroco are you still have problems with this, right now I'm getting .eg,. 

```r
species("Ammodytes marinus", fields= c("DepthRangeShallow", "DepthRangeDeep"))
#>             sciname DepthRangeShallow DepthRangeDeep SpecCode
#> 1 Ammodytes marinus                NA             NA       37
species("Atherion africanum", fields= c("DepthRangeShallow", "DepthRangeDeep"))
#>              sciname DepthRangeShallow DepthRangeDeep SpecCode
#> 1 Atherion africanum                 0             10     1304
```

**Comment by amroco** [comment]
Apologies, haven't used this in a while, but it's looking good to me! Thanks for your help!
